---

- name: "{{ SEC_ID_ENSURE_LAST_LOGGED_USER_DISPLAYED }} | L1 | PATCH | Ensure disable-user-list is enabled"
  lineinfile:
      path: /etc/gdm3/greeter.dconf-defaul
      regexp: '^disable-user-list='
      line: 'disable-user-list=true'
      insertafter: 'banner-message-text='
      create: yes
      owner: root
      group: root
      mode: 0644
  notify: reload gdm
