---

- name: "{{ SEC_ID_ENSURE_LAST_LOGGED_USER_DISPLAYED }} | L1 | PATCH | Ensure last logged in user display is disabled | gdm profile"
  lineinfile:
      path: /etc/dconf/profile/gdm
      regexp: "^{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
      create: true
      mode: 0644
      owner: root
      group: root
  with_items:
      - {regexp: 'user-db', line: 'user-db:user' }
      - {regexp: 'system-db', line: 'system-db:gdm' }
      - {regexp: 'file-db', line: 'file-db:/usr/share/gdm/greeter-dconf-defaults' }

- name: "{{ SEC_ID_ENSURE_LAST_LOGGED_USER_DISPLAYED }} | L1 | PATCH | Ensure last logged in user display is disabled | login screen"
  lineinfile:
      path: /etc/dconf/db/gdm.d/00-login-screen
      regexp: "^{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
      create: true
      mode: 0644
      owner: root
      group: root
  with_items:
      - { regexp: '\[org\/gnome\/login-screen\]', line: '[org/gnome/login-screen]' }
      - { regexp: 'disable-user-list', line: 'disable-user-list=true' }
