---

- name: "{{ SEC_ID_ENSURE_GDM_LOGIN_BANNER_CONFIGURED }} | L1 | PATCH | Ensure GDM login banner is configured | gdm profile"
  lineinfile:
      path: /etc/dconf/profile/gdm
      regexp: "^{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
      create: true
      mode: 0644
      owner: root
      group: root
  with_items:
      - {regexp: 'user-db', line: 'user-db:user' }
      - {regexp: 'system-db', line: 'system-db:gdm' }
      - {regexp: 'file-db', line: 'file-db:/usr/share/gdm/greeter-dconf-defaults' }

- name: "{{ SEC_ID_ENSURE_GDM_LOGIN_BANNER_CONFIGURED }} | L1 | PATCH | Ensure GDM login banner is configured | banner"
  lineinfile:
      path: /etc/dconf/db/gdm.d/01-banner-message
      regexp: "^{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
      create: true
      mode: 0644
      owner: root
      group: root
  with_items:
      - { regexp: '\[org\/gnome\/login-screen\]', line: '[org/gnome/login-screen]' }
      - { regexp: 'banner-message-enable', line: 'banner-message-enable=true' }
      - { regexp: 'banner-message-text', line: "banner-message-text='{{ linuxcis_warning_banner }}' " }
