---

- name: "{{ SEC_ID_ENSURE_GDM_IS_REMOVED }} | L2 | PATCH | Ensure GNOME Display Manager is removed"
  block:
      - name: "{{ SEC_ID_ENSURE_GDM_IS_REMOVED }} | L2 | AUDIT | Ensure GNOME Display Manager is removed | check runlevel"
        fail:
            msg: "System is at runlevel 5 and GDM is installed this can only be removed at Lvl <= 3"
        when:
            - ansible_env.SHLVL > 3

      - name: "{{ SEC_ID_ENSURE_GDM_IS_REMOVED }} | L2 | AUDIT | Ensure GNOME Display Manager is removed | Remove package"
        package:
            name: "{{ GDM_PKG }}"
            state: absent
  when:
      - "GDM_PKG in ansible_facts.packages"
      - not linuxcis_gui
      - SEC_ID_ENSURE_GDM_IS_REMOVED not in disabled_cis_rules
      - linuxcis_level2
  tags:
      - rule_1.8.1
      - level2-server

- name: "{{ SEC_ID_ENSURE_GDM_LOGIN_BANNER_CONFIGURED }} | L1 | PATCH | Ensure GDM login banner is configured"
  include_tasks: "{{ lookup('first_found', dist_tasks) }}"
  vars:
    dist_tasks:
      - "ensure_gdm_banner_configured_{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}.yml"
      - "ensure_gdm_banner_configured_{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
      - "ensure_gdm_banner_configured_{{ ansible_facts.distribution }}.yml"
      - "ensure_gdm_banner_configured_{{ ansible_facts.os_family }}.yml"
  when:
      - "GDM_PKG in ansible_facts.packages"
      - not linuxcis_gui
      - SEC_ID_ENSURE_GDM_LOGIN_BANNER_CONFIGURED not in disabled_cis_rules
  tags:
      - rule_1.8.2
      - level_1

- name: "{{ SEC_ID_ENSURE_LAST_LOGGED_USER_DISPLAYED }} | L1 | PATCH | Ensure last logged in user display is disabled | banner"
  include_tasks: "{{ lookup('first_found', dist_tasks) }}"
  vars:
    dist_tasks:
      - "ensure_display_user_list_enabled_{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}.yml"
      - "ensure_display_user_list_enabled_{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
      - "ensure_display_user_list_enabled_{{ ansible_facts.distribution }}.yml"
      - "ensure_display_user_list_enabled_{{ ansible_facts.os_family }}.yml"
  when:
      - "GDM_PKG in ansible_facts.packages"
      - not linuxcis_gui
      - SEC_ID_ENSURE_LAST_LOGGED_USER_DISPLAYED not in disabled_cis_rules
  tags:
      - rule_1.8.3
      - level_1

- name: "{{ SEC_ID_ENSURE_XDCMP_NOT_ENABLED }} | L1 | PATCH | Ensure XDCMP is not enabled"
  lineinfile:
      path: "/etc/{{ GDM_PKG }}/custom.conf"
      regexp: '^Enable.*=.*true'
      state: absent
      create: true
      owner: root
      group: root
      mode: 0644
  when:
      - "GDM_PKG in ansible_facts.packages"
      - not linuxcis_gui
      - SEC_ID_ENSURE_XDCMP_NOT_ENABLED not in disabled_cis_rules
  tags:
      - rule_1.8.4
