---

- name: "{{ SEC_ID_ENSURE_NFTABLES_LOOPBACK_TRAFFIC_CONFIGURED }} | L1 | AUDIT | Ensure nftables loopback traffic is configured | Gather iif lo accept existence"
  shell: nft list ruleset | awk '/hook input/,/}/' | grep 'iif "lo" accept'
  args:
      warn: false
  changed_when: false
  failed_when: false
  register: linuxcis_nftables_iiflo_out

- name: "{{ SEC_ID_ENSURE_NFTABLES_LOOPBACK_TRAFFIC_CONFIGURED }} | L1 | AUDIT | Ensure nftables loopback traffic is configured | Gather ip saddr existence"
  shell: nft list ruleset | awk '/hook input/,/}/' | grep 'ip saddr'
  args:
      warn: false
  changed_when: false
  failed_when: false
  register: linuxcis_nftables_ipsaddr_out

- name: "{{ SEC_ID_ENSURE_NFTABLES_LOOPBACK_TRAFFIC_CONFIGURED }} | L1 | AUDIT | Ensure nftables loopback traffic is configured | Gather ip6 saddr existence"
  shell: nft list ruleset | awk '/hook input/,/}/' | grep 'ip6 saddr'
  args:
      warn: false
  changed_when: false
  failed_when: false
  register: linuxcis_nftables_ip6saddr_out

- name: "{{ SEC_ID_ENSURE_NFTABLES_LOOPBACK_TRAFFIC_CONFIGURED }} | L1 | PATCH | Ensure nftables loopback traffic is configured | Set iif lo accept rule"
  command: nft add rule inet "{{ linuxcis_nft_tables_tableName }}" input iif lo accept
  args:
      warn: false
  when:
      - '"iif \"lo\" accept" not in linuxcis_nftables_iiflo_out.stdout'

- name: "{{ SEC_ID_ENSURE_NFTABLES_LOOPBACK_TRAFFIC_CONFIGURED }} | L1 | PATCH | Ensure nftables loopback traffic is configured | Set ip sddr rule"
  command: nft add rule inet "{{ linuxcis_nft_tables_tableName }}" input ip saddr 127.0.0.0/8 counter drop
  args:
      warn: false
  when:
      - '"ip saddr 127.0.0.0/8 counter packets 0 bytes 0 drop" not in linuxcis_nftables_ipsaddr_out.stdout'

- name: "{{ SEC_ID_ENSURE_NFTABLES_LOOPBACK_TRAFFIC_CONFIGURED }} | L1 | PATCH | Ensure nftables loopback traffic is configured | Set ip6 saddr rule"
  command: nft add rule inet "{{ linuxcis_nft_tables_tableName }}" input ip6 saddr ::1 counter drop
  args:
      warn: false
  when:
      - '"ip6 saddr ::1 counter packets 0 bytes 0 drop" not in linuxcis_nftables_ip6saddr_out.stdout'
