---

- name: "{{ SEC_ID_ENSURE_NFTABLES_DEFAULT_DENY_FIREWALL_POLICY }} | L1 | AUDIT | Ensure nftables default deny firewall policy | Check for hook input deny policy"
  shell: nft list table inet "{{ linuxcis_nft_tables_tableName }}" | grep 'hook input'
  failed_when: false
  changed_when: false
  register: linuxcis_nftables_inputpolicy_out

- name: "{{ SEC_ID_ENSURE_NFTABLES_DEFAULT_DENY_FIREWALL_POLICY }} | L1 | AUDIT | Ensure nftables default deny firewall policy | Check for hook forward deny policy"
  shell: nft list table inet "{{ linuxcis_nft_tables_tableName }}" | grep 'hook forward'
  failed_when: false
  changed_when: false
  register: linuxcis_nftables_forwardpolicy_out

- name: "{{ SEC_ID_ENSURE_NFTABLES_DEFAULT_DENY_FIREWALL_POLICY }} | L1 | AUDIT | Ensure nftables default deny firewall policy | Check for hook output deny policy"
  shell: nft list table inet "{{ linuxcis_nft_tables_tableName }}" | grep 'hook output'
  failed_when: false
  changed_when: false
  register: linuxcis_nftables_outputpolicy_out

- name: "{{ SEC_ID_ENSURE_NFTABLES_DEFAULT_DENY_FIREWALL_POLICY }} | L1 | AUDIT | Ensure nftables default deny firewall policy | Check for SSH allow"
  shell: nft list table inet "{{ linuxcis_nft_tables_tableName }}" | grep 'ssh'
  failed_when: false
  changed_when: false
  register: linuxcis_nftables_sshallowcheck_out

- name: "{{ SEC_ID_ENSURE_NFTABLES_DEFAULT_DENY_FIREWALL_POLICY }} | L1 | PATCH | Ensure nftables default deny firewall policy | Enable SSH traffic"
  command: nft add rule inet "{{ linuxcis_nft_tables_tableName }}" input tcp dport ssh accept
  when:
      - '"tcp dport ssh accept" not in linuxcis_nftables_sshallowcheck_out.stdout'

- name: "{{ SEC_ID_ENSURE_NFTABLES_DEFAULT_DENY_FIREWALL_POLICY }} | L1 | PATCH | Ensure nftables default deny firewall policy | Set hook input deny policy"
  command: nft chain inet "{{ linuxcis_nft_tables_tableName }}" input { policy drop \; }
  when:
      - '"type filter hook input priority 0; policy drop;" not in linuxcis_nftables_inputpolicy_out.stdout'

- name: "{{ SEC_ID_ENSURE_NFTABLES_DEFAULT_DENY_FIREWALL_POLICY }} | L1 | PATCH | EEnsure nftables default deny firewall policy | Create hook forward deny policy"
  command: nft chain inet "{{ linuxcis_nft_tables_tableName }}" forward { policy drop \; }
  when:
      - '"type filter hook forward priority 0; policy drop;" not in linuxcis_nftables_forwardpolicy_out.stdout'

- name: "{{ SEC_ID_ENSURE_NFTABLES_DEFAULT_DENY_FIREWALL_POLICY }} | L1 | PATCH | Ensure nftables default deny firewall policy | Create hook output deny policy"
  command: nft chain inet "{{ linuxcis_nft_tables_tableName }}" output { policy drop \; }
  when:
      - '"type filter hook output priority 0; policy drop;" not in linuxcis_nftables_outputpolicy_out.stdout'
