---

- name: "{{ SEC_ID_ENSURE_FS_CRAMFS_DISABLED }} | L1 | PATCH | Ensure mounting of cramfs filesystems is disabled "
  include_tasks: disable_filesystem_type.yml
  vars:
    filesystem_type: cramfs
    cis_level: L1
    cis_section: "{{ SEC_ID_ENSURE_FS_CRAMFS_DISABLED }}"
  when:
      - SEC_ID_ENSURE_FS_CRAMFS_DISABLED not in disabled_cis_rules
      - ansible_connection != 'docker'
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.1.1.1
      - cramfs

- name: "{{ SEC_ID_ENSURE_FS_VFAT_DISABLED }} | L2 | PATCH | Ensure mounting of vfat filesystems is disabled"
  include_tasks: disable_filesystem_type.yml
  vars:
    filesystem_type: vfat
    cis_level: L2
    cis_section: "{{ SEC_ID_ENSURE_FS_VFAT_DISABLED }}"
  when:
      - SEC_ID_ENSURE_FS_VFAT_DISABLED not in disabled_cis_rules
      - ansible_connection != 'docker'
      - linuxcis_level2
  tags:
      - level2-server
      - level2-workstation
      - scored
      - patch
      - rule_1.1.1.2
      - squashfs

- name: "{{ SEC_ID_ENSURE_FS_SQUASHFS_DISABLED }} | L2 | PATCH | Ensure mounting of squashfs filesystems is disabled"
  include_tasks: disable_filesystem_type.yml
  vars:
    filesystem_type: squashfs
    cis_level: L2
    cis_section: "{{ SEC_ID_ENSURE_FS_SQUASHFS_DISABLED }}"
  when:
      - SEC_ID_ENSURE_FS_SQUASHFS_DISABLED not in disabled_cis_rules
      - ansible_connection != 'docker'
      - linuxcis_level2
  tags:
      - level2-server
      - level2-workstation
      - scored
      - patch
      - rule_1.1.1.2
      - squashfs

- name: "{{ SEC_ID_ENSURE_FS_UDF_DISABLED }} | L1 | PATCH | Ensure mounting of udf filesystems is disabled"
  include_tasks: disable_filesystem_type.yml
  vars:
    filesystem_type: udf
    cis_level: L1
    cis_section: "{{ SEC_ID_ENSURE_FS_UDF_DISABLED }}"
  when:
      - SEC_ID_ENSURE_FS_UDF_DISABLED not in disabled_cis_rules
      - ansible_connection != 'docker'
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.1.1.3
      - udf
