---

- name: "{{ cis_section }} | {{ cis_level }} | PATCH | Ensure mounting of {{ filesystem_type }} filesystems is disabled | Edit modprobe config"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install {{ filesystem_type }}(\\s|$)"
      line: "install {{ filesystem_type }} /bin/true"
      create: yes
      mode: '0600'
  tags: always

- name: "{{ cis_level }} | PATCH | Ensure mounting of {{ filesystem_type }} filesystems is disabled | Disable {{ filesystem_type }}"
  modprobe:
      name: "{{ filesystem_type }}"
      state: absent
  tags: always
