---

- name: "SECTION | {{ SEC_ID_DISABLE_UNUSED_FILESYSTEMS }} | Disable Unused Filesystems"
  include_tasks: "{{ lookup('first_found', dist_tasks) }}"
  vars:
    dist_tasks:
      - "disable_unused_filesystems_{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}.yml"
      - "disable_unused_filesystems_{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
      - "disable_unused_filesystems_{{ ansible_facts.distribution }}.yml"
      - "disable_unused_filesystems_{{ ansible_facts.os_family }}.yml"
  when:
      - SEC_ID_DISABLE_UNUSED_FILESYSTEMS not in disabled_cis_rules

- name: "SECTION | {{ SEC_ID_FILESYSTEM_CONFIGURATIONS }} | Distribution Specific Order"
  include_tasks: "{{ lookup('first_found', dist_tasks) }}"
  vars:
    dist_tasks:
      - "main_{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}.yml"
      - "main_{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
      - "main_{{ ansible_facts.distribution }}.yml"
      - "main_{{ ansible_facts.os_family }}.yml"
  when:
      - SEC_ID_FILESYSTEM_CONFIGURATIONS not in disabled_cis_rules

- name: |
      "{{ SEC_ID_CONFIGURE_MEDIA_NODEV }} | L1 | PATCH | Ensure removable media partitions include noexec option"
      "{{ SEC_ID_CONFIGURE_MEDIA_NOSUID }} | L1 | PATCH | Ensure nodev option set on removable media partitions"
      "{{ SEC_ID_CONFIGURE_MEDIA_NOEXEC }} | L1 | PATCH | Ensure nosuid option set on removable media partitions"
  debug:
      msg: "--> Not relevant"
  changed_when: false
  when:
      - SEC_ID_CONFIGURE_MEDIA_NODEV not in disabled_cis_rules
      - SEC_ID_CONFIGURE_MEDIA_NOSUID not in disabled_cis_rules
      - SEC_ID_CONFIGURE_MEDIA_NOEXEC not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - notscored
      - audit
      - mounts
      - rule_1.1.19
      - rule_1.1.20
      - rule_1.1.21

- name: "{{ SEC_ID_WORLD_WRITABLE_STICKY_BIT }} | L1 | PATCH | Ensure sticky bit is set on all world-writable directories"
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002 2>/dev/null | xargs chmod a+t
  args:
      warn: no
  changed_when: false
  failed_when: false
  when:
      - SEC_ID_WORLD_WRITABLE_STICKY_BIT not in disabled_cis_rules
  tags:
      - skip_ansible_lint
      - level1-server
      - level1-workstation
      - patch
      - stickybits
      - permissons
      - rule_1.1.22

- name: "{{ SEC_ID_DISABLE_AUTOMOUNT }} | L1 | PATCH | Disable Automounting"
  service:
      name: autofs
      enabled: no
  when:
      - not linuxcis_allow_autofs
      - "'autofs' in ansible_facts.packages"
      - SEC_ID_DISABLE_AUTOMOUNT not in disabled_cis_rules
      - linuxcis_level2
  tags:
      - level1-server
      - level2-workstation
      - patch
      - mounts
      - automounting
      - rule_1.1.23

- name: "{{ SEC_ID_DISABLE_USB_STORAGE }} | L1 | PATCH | Disable USB Storage"
  block:
      - name: "{{ SEC_ID_DISABLE_USB_STORAGE }} | L1 | PATCH | Disable USB Storage | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/CIS.conf
            regexp: "^(#)?install usb-storage(\\s|$)"
            line: "install usb-storage /bin/true"
            create: yes
            owner: root
            group: root
            mode: 0640

      - name: "{{ SEC_ID_DISABLE_USB_STORAGE }} | L1 | PATCH | Disable USB Storage | Edit modprobe config"
        modprobe:
            name: usb-storage
            state: absent
        when: not system_is_container
  when:
      - SEC_ID_DISABLE_USB_STORAGE not in disabled_cis_rules
      - linuxcis_level2
  tags:
      - level1-server
      - level2-workstation
      - patch
      - mounts
      - removable_storage
      - rule_1.1.24
