---

- name: "{{ SEC_ID_ENSURE_UPDATES_AND_PATCHES_INSTALLED }} | L1 | PATCH | Ensure updates, patches, and additional security software are installed"
  package:
      name: "*"
      state: latest
  when:
      - SEC_ID_ENSURE_UPDATES_AND_PATCHES_INSTALLED not in disabled_cis_rules
      - not system_is_ec2
  tags:
      - level1
      - patch
      - rule_1.9
      - skip_ansible_lint
#   vars:
#       ansible_python_interpreter: /bin/python
