---

namespace: "db0"
name: "os_hardening"
version: "0.1.0"
readme: "README.md"
authors:
    - "Konstantinos Thoukydydis"
dependencies:
    community.general: "*"
license:
    - "MIT"
tags:
    - linux
    - collection
repository: "https://github.com/db0/os-hardening"
issues: "https://github.com/db0/os-hardening/issues"
description: Ansible collection for OS-agnostic Hardening
