---

namespace: "db0"
name: "os_hardening"
version: "1.0.0"
readme: "README.md"
authors:
    - "Konstantinos Thoukydidis"
dependencies:
    community.general: "*"
license:
    - "MIT"
tags:
    - linux
    - collection
    - hardening
    - cis
    - redhat
    - centos
    - debian
    - ubuntu
repository: "https://github.com/db0/os-hardening"
issues: "https://github.com/db0/os-hardening/issues"
description: Ansible collection for OS-agnostic Hardening
