---

- name: "{{ SEC_ID_ENSURE_XORG_NOT_INSTALLED }} | L1 | AUDIT | Ensure X Window System is not installed | capture xorg-x11 packages"
  shell: rpm -qa | grep xorg-x11
  failed_when: xorg_x11_installed.rc >=2
  check_mode: false
  changed_when: false
  register: xorg_x11_installed
  tags: always

- name: "{{ SEC_ID_ENSURE_XORG_NOT_INSTALLED }} | L1 | PATCH | Ensure X Window System is not installed | remove packages if found"
  shell: "dnf remove {{ item }}"
  loop:
      - xorg_x11_installed.stdout_lines
  when: xorg_x11_installed.stdout | length > 0
  tags: always
