---

- name: "{{ SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE }} | L1 | PATCH | Ensure systemd-timesyncd is configured"
  block:
      - name: "{{ SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE }} | L1 | PATCH | Ensure systemd-timesyncd is configured | Remove ntp and chrony"
        apt:
            name:
            - ntp
            - chrony
            state: absent

      - name: "{{ SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE }} | L1 | PATCH | Ensure systemd-timesyncd is configured | Set configuration for systemd-timesyncd"
        lineinfile:
            path: /etc/systemd/timesyncd.conf
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
            insertafter: "{{ item.insertafter }}"
        with_items:
            - { regexp: '^\[Time\]', line: '[Time]', insertafter: EOF }
            - { regexp: '^#NTP|^NTP', line: 'NTP={{ debiancis_ntp_server_list }}', insertafter: '\[Time\]' }
            - { regexp: '^#FallbackNTP|^FallbackNTP', line: 'FallbackNTP={{ debiancis_ntp_fallback_server_list }}', insertafter: '\[Time\]' }
            - { regexp: '^#RootDistanceMaxSec|^RootDistanceMaxSec', line: 'RootDistanceMaxSec=1', insertafter: '\[Time\]'}

      - name: "{{ SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE }} | L1 | PATCH | Ensure systemd-timesyncd is configured | Start and enable the systemd-timesyncd service"
        systemd:
            name: systemd-timesyncd.service
            state: started
            enabled: yes
            masked: no

      - name: "{{ SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE }} | L1 | PATCH | Ensure systemd-timesyncd is configured | Set timedatectl to ntp"
        command: timedatectl set-ntp true
  when:
      - SEC_ID_ENSURE_SYSTEMD_TIMESYNCD_CONFIGURED not in disabled_cis_rules
      - linuxcis_time_synchronization == "systemd-timesyncd"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - manual
      - patch
      - rule_2.1.1.2
      - systemd-timesyncd

- name: "{{ SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE }} | L1 | PATCH | Ensure chrony is configured"
  block:
      - name: "{{ SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE }} | L1 | PATCH | Ensure chrony is configured | Remove ntp"
        apt:
            name: ntp
            state: absent

      - name: "{{ SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE }} | L1 | PATCH | Ensure chrony is configured | Disable/Mask systemd-timesyncd"
        systemd:
            name: systemd-timesyncd
            state: stopped
            enabled: no
            masked: yes

      - name: "{{ SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE }} | L1 | AUDIT | Ensure chrony is configured | Check for chrony user"
        shell: grep {{ debiancis_chrony_user }} /etc/passwd
        changed_when: false
        failed_when: false
        check_mode: false
        register: debiancis_chrony_user_status

      - name: "{{ SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE }} | L1 | PATCH | Ensure chrony is configured | Set chrony.conf file"
        template:
            src: chrony.conf.j2
            dest: /etc/chrony/chrony.conf
            owner: root
            group: root
            mode: 0644

      - name: "{{ SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE }} | L1 | PATCH | Ensure chrony is configured | Create chrony user"
        user:
            name: "{{ debiancis_chrony_user }}"
            shell: /usr/sbin/nologin
            system: true
        when: debiancis_chrony_user_status.stdout | length > 0

      - name: "{{ SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE }} | L1 | PATCH | Ensure chrony is configured | Set option to use chrony user"
        lineinfile:
            path: /etc/default/chrony
            regexp: '^DAEMON_OPTS'
            line: 'DAEMON_OPTS="-u {{ debiancis_chrony_user }}"'
  when:
      - SEC_ID_ENSURE_CHRONY_CONFIGURED not in disabled_cis_rules
      - linuxcis_time_synchronization == "chrony"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.1.1.3
      - chrony

- name: "{{ SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE }} | L1 | PATCH | Ensure ntp is configured"
  block:
      - name: "{{ SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE }} | L1 | PATCH | Ensure ntp is configured | Remove chrony"
        apt:
            name: chrony
            state: absent

      - name: "{{ SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE }} | L1 | Ensure ntp is configured | Disable/Mask systemd-timesyncd"
        systemd:
            name: systemd-timesyncd
            state: stopped
            enabled: no
            masked: yes

      - name: "{{ SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE }} | L1 | PATCH | Ensure ntp is configured | Set ntp.conf settings"
        template:
            src: ntp.conf.j2
            dest: /etc/ntp.conf
            owner: root
            group: root
            mode: 0644

      - name: "{{ SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE }} | L1 | PATCH | Ensure ntp is configured | Modify sysconfig/ntpd"
        lineinfile:
            path: /etc/sysconfig/ntpd
            regexp: "{{ item.regexp }}"
            line: "{{ item. line }}"
            create: yes
        with_items:
            - { regexp: '^OPTIONS', line: 'OPTIONS="-u ntp:ntp"'}
            - { regexp: '^NTPD_OPTIONS', line: 'NTPD_OPTIONS="-u ntp:ntp"' }

      - name: "{{ SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE }} | L1 | PATCH | Ensure ntp is configured | Modify /etc/init.d/npt"
        lineinfile:
            path: /etc/init.d/ntp
            regexp: '^RUNAUSER'
            line: 'RUNAUSER=npt'
  when:
      - SEC_ID_ENSURE_NTPD_CONFIGURED not in disabled_cis_rules
      - linuxcis_time_synchronization == "ntp"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.1.1.4
      - ntp
