---

- name: "{{ SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE }} | L1 | PATCH | Ensure time synchronization is in use | service start"
  service:
      name: "{{ linuxcis_time_synchronization }}d"
      state: started
      enabled: yes
  when:
      - SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE not in disabled_cis_rules
      - not linuxcis_system_is_container
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.2.1.1

- name: "{{ SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE }} | L1 | PATCH | Ensure time synchronization is in use - service stop ntp"
  service:
      name: ntpd
      state: stopped
      enabled: no
  when:
      - "'ntp' in ansible_facts.packages"
      - linuxcis_time_synchronization == "chrony"
      - SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE not in disabled_cis_rules
      - not linuxcis_system_is_container
  tags:
      - level1
      - patch
      - rule_2.2.1.1

- name: "{{ SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE }} | L1 | PATCH | Ensure time synchronization is in use - service stop chrony"
  service:
      name: chronyd
      state: stopped
      enabled: no
  when:
      - linuxcis_time_synchronization == "ntp" and "'chrony' in ansible_facts.packages"
      - SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE not in disabled_cis_rules
      - not linuxcis_system_is_container
  tags:
      - level1
      - patch
      - rule_2.2.1.1

- name: "{{ SEC_ID_ENSURE_CHRONY_CONFIGURED }} | L1 | PATCH | Ensure chrony is configured"
  block:
      - name: "{{ SEC_ID_ENSURE_CHRONY_CONFIGURED }} | L1 | PATCH | Ensure chrony is configured | modify /etc/chrony.conf"
        template:
            src: chrony.conf.j2
            dest: /etc/chrony.conf
            owner: root
            group: root
            mode: 0644

      - name: "{{ SEC_ID_ENSURE_CHRONY_CONFIGURED }} | L1 | PATCH | Ensure chrony is configured | modify /etc/sysconfig/chronyd"
        lineinfile:
            dest: /etc/sysconfig/chronyd
            regexp: "^(#)?OPTIONS"
            line: "OPTIONS=\"-u chrony\""
            state: present
            create: yes
            owner: root
            group: root
            mode: 0640
  when:
      - linuxcis_time_synchronization == "chrony"
      - SEC_ID_ENSURE_CHRONY_CONFIGURED not in disabled_cis_rules
      - not linuxcis_system_is_container
  tags:
      - level1
      - patch
      - rule_2.2.1.2

- name: "{{ SEC_ID_ENSURE_NTPD_CONFIGURED }} | L1 | PATCH | Ensure ntp is configured"
  block:
      - name: "{{ SEC_ID_ENSURE_NTPD_CONFIGURED }} | L1 | PATCH | Ensure ntp is configured | modify /etc/ntp.conf"
        template:
            src: ntp.conf.j2
            dest: /etc/ntp.conf
            owner: root
            group: root
            mode: 0644

      - name: "{{ SEC_ID_ENSURE_NTPD_CONFIGURED }} | L1 | PATCH | Ensure ntp is configured | modify /etc/sysconfig/ntpd"
        lineinfile:
            dest: /etc/sysconfig/ntpd
            regexp: "^(#)?OPTIONS"
            line: "OPTIONS=\"-u ntp:ntp\""

      - name: "{{ SEC_ID_ENSURE_NTPD_CONFIGURED }} | L1 | PATCH | Ensure ntp is configured | modify /usr/lib/systemd/system/ntpd.service"
        lineinfile:
            dest: /usr/lib/systemd/system/ntpd.service
            regexp: "^(#)?ExecStart"
            line: "ExecStart=/usr/sbin/ntpd -u ntp:ntp $OPTIONS"
  when:
      - linuxcis_time_synchronization == "ntp"
      - SEC_ID_ENSURE_NTPD_CONFIGURED not in disabled_cis_rules
      - not linuxcis_system_is_container
  tags:
      - level1
      - patch
      - rule_2.2.1.3
