---

- name: "{{ SEC_ID_ENSURE_CHRONY_CONFIGURED }} | L1 | PATCH | Ensure chrony is configured"
  block:
      - name: "{{ SEC_ID_ENSURE_CHRONY_CONFIGURED }} | L1 | PATCH | Ensure chrony is configured | Set configuration"
        template:
            src: chrony.conf.j2
            dest: /etc/chrony.conf
            owner: root
            group: root
            mode: 0644

      - name: "{{ SEC_ID_ENSURE_CHRONY_CONFIGURED }} | L1 | PATCH | Ensure chrony is configured | modify /etc/sysconfig/chronyd | 1"
        lineinfile:
            dest: /etc/sysconfig/chronyd
            regexp: "^(#)?OPTIONS"
            line: "OPTIONS=\"-u chrony\""
            state: present
            create: true
            mode: 0644
  when:
      - linuxcis_time_synchronization == "chrony"
      - SEC_ID_ENSURE_CHRONY_CONFIGURED not in disabled_cis_rules
      - not system_is_container
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.2.1.2
