---

- name: "SECTION | {{ SEC_ID_TIME_SYNCHRONIZATION }} | Time Synchronization"
  include_tasks: "time_synchronization.yml"

- name: "{{ SEC_ID_X11_COMPONENTS_NOT_INSTALLED }} | L1 | PATCH | Ensure X11 Server components are not installed"
  package:
      state: absent
      name: "{{ SEC_2_2_2_XORG_PKG }}"
#   vars:
#       ansible_python_interpreter: /bin/python
  when:
      - not linuxcis_xwindows_required
      - SEC_ID_TIME_SYNCHRONIZATION not in disabled_cis_rules
  tags:
      - level1
      - scored
      - xwindows
      - patch
      - rule_2.2.2

- name: "{{ SEC_ID_AVAHI_SERVER_NOT_INSTALLED }} | L1 | PATCH | Ensure Avahi Server is not installed | disabled"
  service:
      name: avahi-daemon
      state: stopped
      enabled: no
  when:
      - not linuxcis_avahi_server
      - "'avahi' in ansible_facts.packages"
      - SEC_ID_AVAHI_SERVER_NOT_INSTALLED not in disabled_cis_rules
  tags:
      - level1
      - scored
      - avahi
      - services
      - patch
      - rule_2.2.3

- name: "{{ SEC_ID_CUPS_SERVER_NOT_INSTALLED }} | L1 | PATCH | Ensure CUPS is not installed"
  package:
      name: cups
      state: absent
#   vars:
#       ansible_python_interpreter: /bin/python
  when:
      - not linuxcis_cups_server
      - "'cups' in ansible_facts.packages"
      - SEC_ID_CUPS_SERVER_NOT_INSTALLED not in disabled_cis_rules
  tags:
      - level1
      - scored
      - cups
      - services
      - patch
      - rule_2.2.4

- name: "{{ SEC_ID_DHCP_SERVER_NOT_INSTALLED }} | L1 | PATCH | Ensure DHCP Server is not installed"
  package:
      name: dhcp
      state: absent
#   vars:
#       ansible_python_interpreter: /bin/python
  when:
      - not linuxcis_dhcp_server
      - "'dhcp' in ansible_facts.packages"
      - SEC_ID_DHCP_SERVER_NOT_INSTALLED not in disabled_cis_rules
  tags:
      - level1
      - scored
      - dhcp
      - services
      - patch
      - rule_2.2.5

- name: "{{ SEC_ID_LDAP_SERVER_NOT_INSTALLED }} | L1 | PATCH | Ensure LDAP server is not installed"
  package:
      name: openldap-servers
      state: absent
#   vars:
#       ansible_python_interpreter: /bin/python
  when:
      - not linuxcis_ldap_server
      - "'openldap-servers' in ansible_facts.packages"
      - SEC_ID_LDAP_SERVER_NOT_INSTALLED not in disabled_cis_rules
  tags:
      - level1
      - scored
      - ldap
      - services
      - patch
      - rule_2.2.6

- name: "{{ SEC_ID_DNS_SERVER_NOT_INSTALLED }} | L1 | PATCH | Ensure DNS server is not installed"
  package:
      name: bind
      state: absent
#   vars:
#       ansible_python_interpreter: /bin/python
  when:
      - not linuxcis_named_server
      - "'bind' in ansible_facts.packages"
      - SEC_ID_DNS_SERVER_NOT_INSTALLED not in disabled_cis_rules
  tags:
      - level1
      - scored
      - dns
      - services
      - patch
      - rule_2.2.7

- name: "{{ SEC_ID_FTP_SERVER_NOT_INSTALLED }} | L1 | PATCH | Ensure FTP server is not installed"
  package:
      name: vsftpd
      state: absent
#   vars:
#       ansible_python_interpreter: /bin/python
  when:
      - not linuxcis_vsftpd_server
      - "'vsftpd' in ansible_facts.packages"
      - SEC_ID_FTP_SERVER_NOT_INSTALLED not in disabled_cis_rules
  tags:
      - level1
      - scored
      - ftp
      - services
      - patch
      - rule_2.2.8

- name: "{{ SEC_ID_HTTP_SERVER_NOT_INSTALLED }} | L1 | PATCH | Ensure HTTP server is not installed"
  package:
      name: httpd
      state: absent
#   vars:
#       ansible_python_interpreter: /bin/python
  when:
      - not linuxcis_httpd_server
      - "'httpd' in ansible_facts.packages"
      - SEC_ID_HTTP_SERVER_NOT_INSTALLED not in disabled_cis_rules
  tags:
      - level1
      - scored
      - ldap
      - services
      - patch
      - rule_2.2.9

- name: "{{ SEC_ID_IMAP_POP3_SERVER_NOT_INSTALLED }} | L1 | PATCH | Ensure IMAP and POP3 server is not installed"
  package:
      name: dovecot
      state: absent
#   vars:
#       ansible_python_interpreter: /bin/python
  when:
      - not linuxcis_dovecot_server
      - "'dovecot' in ansible_facts.packages"
      - SEC_ID_IMAP_POP3_SERVER_NOT_INSTALLED not in disabled_cis_rules
  tags:
      - level1
      - scored
      - dovecot
      - services
      - patch
      - rule_2.2.10

- name: "{{ SEC_ID_SAMBA_SERVER_NOT_INSTALLED }} | L1 | PATCH | Ensure Samba server is not installed"
  package:
      name: samba
      state: absent
#   vars:
#       ansible_python_interpreter: /bin/python
  when:
      - not linuxcis_smb_server
      - "'samba' in ansible_facts.packages"
      - SEC_ID_SAMBA_SERVER_NOT_INSTALLED not in disabled_cis_rules
  tags:
      - level1
      - scored
      - samba
      - services
      - patch
      - rule_2.2.11

- name: "{{ SEC_ID_HTTP_PROXY_SERVER_NOT_INSTALLED }} | L1 | PATCH | Ensure HTTP Proxy server is not installed"
  package:
      name: squid
      state: absent
#   vars:
#       ansible_python_interpreter: /bin/python
  when:
      - not linuxcis_squid_server
      - "'squid' in ansible_facts.packages"
      - SEC_ID_HTTP_PROXY_SERVER_NOT_INSTALLED not in disabled_cis_rules
  tags:
      - level1
      - scored
      - squid
      - services
      - patch
      - rule_2.2.12

- name: "{{ SEC_ID_NET_SNMP_NOT_INSTALLED }} | L1 | PATCH | Ensure net-snmp is not installed"
  package:
      name: net-snmp
      state: absent
#   vars:
#       ansible_python_interpreter: /bin/python
  when:
      - not linuxcis_snmp_server
      - "'net-snmp' in ansible_facts.packages"
      - SEC_ID_NET_SNMP_NOT_INSTALLED not in disabled_cis_rules
  tags:
      - level1
      - scored
      - squid
      - services
      - patch
      - rule_2.2.13

- name: "{{ SEC_ID_NIS_SERVER_NOT_INSTALLED }} | L1 | PATCH | Ensure NIS server is not installed"
  package:
      name: ypserv
      state: absent
#   vars:
#       ansible_python_interpreter: /bin/python
  when:
      - not linuxcis_nis_server
      - "'ypserv' in ansible_facts.packages"
      - SEC_ID_NIS_SERVER_NOT_INSTALLED not in disabled_cis_rules
  tags:
      - level1
      - scored
      - nis
      - services
      - patch
      - rule_2.2.14

- name: "{{ SEC_ID_TELNET_SERVER_NOT_INSTALLED }} | L1 | PATCH | Ensure telnet-server is not installed"
  package:
      name: telnet-server
      state: absent
#   vars:
#       ansible_python_interpreter: /bin/python
  when:
      - not linuxcis_telnet_server
      - "'telnet-server' in ansible_facts.packages"
      - SEC_ID_TELNET_SERVER_NOT_INSTALLED not in disabled_cis_rules
  tags:
      - level1
      - scored
      - telnet
      - services
      - patch
      - rule_2.2.15

- name: "{{ SEC_ID_MTA_CONFIGURED_LOCAL_ONLY }} | L1 | PATCH | Ensure mail transfer agent is configured for local-only mode"
  lineinfile:
      dest: /etc/postfix/main.cf
      regexp: "^(#)?inet_interfaces"
      line: "inet_interfaces = loopback-only"
  notify: restart postfix
  when:
      - not linuxcis_is_mail_server
      - "'postfix' in ansible_facts.packages"
      - SEC_ID_MTA_CONFIGURED_LOCAL_ONLY not in disabled_cis_rules
  tags:
      - level1
      - patch
      - rule_2.2.16

- name: "{{ SEC_ID_NFS_UTILS_NOT_INSTALLED }} | L1 | PATCH | Ensure nfs-utils is not installed or the nfs-server service is masked"
  block:
      - name: "{{ SEC_ID_NFS_UTILS_NOT_INSTALLED }} | L1 | PATCH | Ensure nfs-utils is not installed or the nfs-server service is masked | nfs-utils "
        package:
            name: nfs-utils
            state: absent
        # vars:
        #     ansible_python_interpreter: /bin/python
        when:
            - not linuxcis_nfs_rpc_server and not linuxcis_nfs_server

      - name: "{{ SEC_ID_NFS_UTILS_NOT_INSTALLED }} | L1 | PATCH | Ensure nfs-utils is not installed or the nfs-server service is masked | nfs-server "
        systemd:
            name: nfs-server
            masked: true
        when:
            - linuxcis_nfs_rpc_server and not linuxcis_nfs_server
  when:
      - "'nfs-utils' in ansible_facts.packages"
      - SEC_ID_NFS_UTILS_NOT_INSTALLED not in disabled_cis_rules
  tags:
      - level1
      - scored
      - nfs
      - services
      - patch
      - rule_2.2.17

- name: "{{ SEC_ID_RPC_BIND_NOT_INSTALLED }} | L1 | PATCH | Ensure rpcbind is not installed or the rpcbind services are masked"
  block:
      - name: "{{ SEC_ID_RPC_BIND_NOT_INSTALLED }} | L1 | PATCH | Ensure rpcbind is not installed or the rpcbind services are masked | rpcbind"
        package:
            name: rpcbind
            state: absent
        # vars:
        #     ansible_python_interpreter: /bin/python
        when:
            - not linuxcis_nfs_rpc_server and not linuxcis_rpc_server

      - name: "{{ SEC_ID_RPC_BIND_NOT_INSTALLED }} | L1 | PATCH | Ensure rpcbind is not installed or the rpcbind services are masked | rpcbind-server"
        systemd:
            name: rpcbind
            masked: true
        when:
            - linuxcis_nfs_rpc_server and not linuxcis_rpc_server

      - name: "{{ SEC_ID_RPC_BIND_NOT_INSTALLED }} | L1 | PATCH | Ensure rpcbind is not installed or the rpcbind services are masked | rpcbind-server"
        systemd:
            name: rpcbind.socket
            masked: true
        when:
            - linuxcis_nfs_rpc_server and not linuxcis_rpc_server
  when:
      - "'rpcbind' in ansible_facts.packages"
      - SEC_ID_RPC_BIND_NOT_INSTALLED not in disabled_cis_rules
  tags:
      - level1
      - scored
      - rpc
      - services
      - patch
      - rule_2.2.18

- name: "{{ SEC_ID_RSYNC_NOT_INSTALLED }} | L1 | PATCH | Ensure rsync is not installed or the rsyncd services are masked"
  block:
      - name: "{{ SEC_ID_RSYNC_NOT_INSTALLED }} | L1 | PATCH | Ensure rsync is not installed or the rsyncd services are masked | pkg removal"
        package:
            name: rsync
            state: absent
        # vars:
        #     ansible_python_interpreter: /bin/python

      - name: "{{ SEC_ID_RSYNC_NOT_INSTALLED }} | L1 | PATCH | Ensure rsync is not installed or the rsyncd services are masked | Mask "
        systemd:
            name: rsyncd
            masked: true

  when:
      - not linuxcis_rsyncd_server
      - "'rsync' in ansible_facts.packages"
      - SEC_ID_RSYNC_NOT_INSTALLED not in disabled_cis_rules
  tags:
      - level1
      - scored
      - rsync
      - services
      - patch
      - rule_2.2.19
