---

- name: "{{ SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE }} | L1 | PATCH | Ensure time synchronization is in use | service install"
  package:
      name: "{{ linuxcis_time_synchronization }}"
      state: present
  when:
      - SEC_ID_ENSURE_TIME_SYNCHRONIZATION_IN_USE not in disabled_cis_rules
      - not linuxcis_system_is_container
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_2.2.1.1

- name: "SECTION | {{ SEC_ID_TIME_SYNCHRONIZATION }} | Distribution Specific Order"
  include_tasks: "{{ lookup('first_found', dist_tasks) }}"
  vars:
    dist_tasks:
      - "ensure_time_synchronization_configured_{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}.yml"
      - "ensure_time_synchronization_configured_{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
      - "ensure_time_synchronization_configured_{{ ansible_facts.distribution }}.yml"
      - "ensure_time_synchronization_configured_{{ ansible_facts.os_family }}.yml"
