---

- name: "{{ SEC_ID_ENSURE_AUDIT_BACKLOG_LIMIT_SUFFICIENT }} | L2 | AUDIT | Ensure audit_backlog_limit is sufficient | Grep GRUB_CMDLINE_LINUX parameter"
  shell: grep 'GRUB_CMDLINE_LINUX=' /etc/default/grub | cut -f2 -d'"'
  changed_when: false
  failed_when: false
  register: linuxcis_backlog_grub_cmdline_linux_settings_out

- name: "{{ SEC_ID_ENSURE_AUDIT_BACKLOG_LIMIT_SUFFICIENT }} | L2 | PATCH | Ensure audit_backlog_limit is sufficient | Set audit_backlog_limit if not configured"
  lineinfile:
      dest: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX='
      line: 'GRUB_CMDLINE_LINUX="{{ linuxcis_backlog_grub_cmdline_linux_settings_out.stdout }} audit_backlog_limit={{ linuxcis_audit_backlog_limit }}"'
  notify: grub2cfg
  when: '"audit_backlog_limit" not in linuxcis_backlog_grub_cmdline_linux_settings_out.stdout'

- name: "{{ SEC_ID_ENSURE_AUDIT_BACKLOG_LIMIT_SUFFICIENT }} | L2 | PATCH | Ensure audit_backlog_limit is sufficient | Adjust audit_backlog_limit if exists"
  replace:
      dest: /etc/default/grub
      regexp: 'audit_backlog_limit=([^\D]+)'
      replace: 'audit_backlog_limit={{ linuxcis_audit_backlog_limit }}'
  notify: grub2cfg
  when: '"audit_backlog_limit" in linuxcis_backlog_grub_cmdline_linux_settings_out.stdout'
