---
- name: "{{ SEC_ID_ENSURE_AUDITD_INSTALLED }} | L2 | PATCH | Ensure auditd is installed"
  yum:
      name: "{{ AUDITD_PKG }}"
      state: present
  when:
      - SEC_ID_ENSURE_AUDITD_INSTALLED not in disabled_cis_rules
      - linuxcis_level2
  notify: restart auditd
  tags:
      - level2-server
      - level2-workstation
      - patch
      - auditd
      - rule_4.1.1.1

- name: "{{ SEC_ID_ENSURE_AUDITD_ENABLED }} | L2 | PATCH | Ensure auditd service is enabled and running"
  service:
      name: auditd
      state: started
      enabled: yes
  when:
      - not linuxcis_skip_for_travis
      - SEC_ID_ENSURE_AUDITD_ENABLED not in disabled_cis_rules
      - not system_is_container
      - linuxcis_level2
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.1.2

- name: "{{ SEC_ID_ENSURE_AUDITING_FOR_PRE_AUDITD_SERVICES_ENABLED }} | L2 | PATCH | Ensure auditing for processes that start prior to auditd is enabled"
  include_tasks: ensure_auditing_for_process_prior_to_auditd.yml
  when:
      - SEC_ID_ENSURE_AUDITING_FOR_PRE_AUDITD_SERVICES_ENABLED not in disabled_cis_rules
      - linuxcis_level2
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.1.3
