---

- name: "SECTION | {{ SEC_ID_ENSURE_AUDITING_ENABLED }} | Ensure auditing is enabled"
  include_tasks: ensure_auditing_enabled_RedHat.yml

- name: "SECTION | {{ SEC_ID_CONFIGURE_DATA_RETENTION }} | Configure Data Retention"
  include_tasks: configure_data_retention_RedHat.yml

- name: "{{ SEC_ID_ENSURE_SUDOERS_CHANGES_COLLECTED }} | L2 | PATCH | Ensure changes to system administration scope (sudoers) is collected"
  debug:
    msg: "Control being set via Handler 'update auditd' which writes to /etc/audit.d/99_auditd.rules"
  notify: update auditd
  when:
      - SEC_ID_ENSURE_SUDOERS_CHANGES_COLLECTED not in disabled_cis_rules
      - linuxcis_level2
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.14

- name: "{{ SEC_ID_ENSURE_LOGIN_LOGOUT_EVENTS_COLLECTED }} | L2 | PATCH | Ensure login and logout events are collected"
  debug:
    msg: "Control being set via Handler 'update auditd' which writes to /etc/audit.d/99_auditd.rules"
  notify: update auditd
  when:
      - SEC_ID_ENSURE_LOGIN_LOGOUT_EVENTS_COLLECTED not in disabled_cis_rules
      - linuxcis_level2
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.7

- name: "{{ SEC_ID_ENSURE_SESSION_INIT_INFO_COLLECTED }} | L2 | PATCH | Ensure session initiation information is collected"
  debug:
    msg: "Control being set via Handler 'update auditd' which writes to /etc/audit.d/99_auditd.rules"
  notify: update auditd
  when:
      - SEC_ID_ENSURE_SESSION_INIT_INFO_COLLECTED not in disabled_cis_rules
      - linuxcis_level2
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.8

- name: "{{ SEC_ID_ENSURE_DATE_TIME_EVENTS_COLLECTED }} | L2 | PATCH | Ensure events that modify date and time information are collected"
  debug:
    msg: "Control being set via Handler 'update auditd' which writes to /etc/audit.d/99_auditd.rules"
  notify: update auditd
  when:
      - SEC_ID_ENSURE_DATE_TIME_EVENTS_COLLECTED not in disabled_cis_rules
      - linuxcis_level2
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.3

- name: "{{ SEC_ID_ENSURE_MANDATORY_ACCESS_CONTROL_EVENTS_COLLECTED }} | L2 | PATCH | Ensure events that modify the system's Mandatory Access Controls are collected"
  debug:
    msg: "Control being set via Handler 'update auditd' which writes to /etc/audit.d/99_auditd.rules"
  notify: update auditd
  when:
      - SEC_ID_ENSURE_MANDATORY_ACCESS_CONTROL_EVENTS_COLLECTED not in disabled_cis_rules
      - linuxcis_level2
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.6

- name: "{{ SEC_ID_ENSURE_NETWORK_ENVIRONMENT_EVENTS_COLLECTED }} | L2 | PATCH | Ensure events that modify the system's network environment are collected"
  debug:
    msg: "Control being set via Handler 'update auditd' which writes to /etc/audit.d/99_auditd.rules"
  notify: update auditd
  when:
      - SEC_ID_ENSURE_NETWORK_ENVIRONMENT_EVENTS_COLLECTED not in disabled_cis_rules
      - linuxcis_level2
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.5

- name: "{{ SEC_ID_ENSURE_DISC_ACC_CTRL_PERM_COLLECTED }} | L2 | PATCH | Ensure discretionary access control permission modification events are collected"
  debug:
    msg: "Control being set via Handler 'update auditd' which writes to /etc/audit.d/99_auditd.rules"
  notify: update auditd
  when:
      - SEC_ID_ENSURE_SESSION_INIT_INFO_COLLECTED not in disabled_cis_rules
      - linuxcis_level2
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - automated
      - rule_4.1.9

- name: "{{ SEC_ID_ENSURE_UNAUTH_FILE_ACCESS_COLLECTED }} | L2 | PATCH | Ensure unsuccessful unauthorized file access attempts are collected"
  debug:
    msg: "Control being set via Handler 'update auditd' which writes to /etc/audit.d/99_auditd.rules"
  notify: update auditd
  when:
      - SEC_ID_ENSURE_UNAUTH_FILE_ACCESS_COLLECTED not in disabled_cis_rules
      - linuxcis_level2
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.10

- name: "{{ SEC_ID_ENSURE_USER_GROUP_EVENTS_COLLECTED }} | L2 | PATCH | Ensure events that modify user/group information are collected"
  debug:
    msg: "Control being set via Handler 'update auditd' which writes to /etc/audit.d/99_auditd.rules"
  notify: update auditd
  when:
      - SEC_ID_ENSURE_USER_GROUP_EVENTS_COLLECTED not in disabled_cis_rules
      - linuxcis_level2
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.4

- name: "{{ SEC_ID_ENSURE_FS_MOUNTS_COLLECTED }} | L2 | PATCH | Ensure successful file system mounts are collected"
  debug:
    msg: "Control being set via Handler 'update auditd' which writes to /etc/audit.d/99_auditd.rules"
  notify: update auditd
  when:
      - SEC_ID_ENSURE_FS_MOUNTS_COLLECTED not in disabled_cis_rules
      - linuxcis_level2
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - automated
      - rule_4.1.12

- name: "{{ SEC_ID_ENSURE_PRIV_COMMANDS_COLLECTED }} | L2 | PATCH | Ensure use of privileged commands is collected"
  debug:
    msg: "Control being set via Handler 'update auditd' which writes to /etc/audit.d/99_auditd.rules"
  notify: update auditd
  when:
      - SEC_ID_ENSURE_PRIV_COMMANDS_COLLECTED not in disabled_cis_rules
      - linuxcis_level2
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.11

- name: "{{ SEC_ID_ENSURE_FILE_DELETION_EVENTS_COLLECTED }} | L2 | PATCH | Ensure file deletion events by users are collected"
  debug:
    msg: "Control being set via Handler 'update auditd' which writes to /etc/audit.d/99_auditd.rules"
  notify: update auditd
  when:
      - SEC_ID_ENSURE_FILE_DELETION_EVENTS_COLLECTED not in disabled_cis_rules
      - linuxcis_level2
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.13

- name: "{{ SEC_ID_ENSURE_KERNEL_MODULE_ACTIONS_COLLECTED }} | L2 | PATCH | Ensure kernel module loading and unloading is collected"
  debug:
    msg: "Control being set via Handler 'update auditd' which writes to /etc/audit.d/99_auditd.rules"
  notify: update auditd
  when:
      - SEC_ID_ENSURE_KERNEL_MODULE_ACTIONS_COLLECTED not in disabled_cis_rules
      - linuxcis_level2
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.16

- name: "{{ SEC_ID_ENSURE_SUDO_COMMANDS_COLLECTED }} | L2 | PATCH | Ensure system administrator command executions (sudo) are collected"
  debug:
    msg: "Control being set via Handler 'update auditd' which writes to /etc/audit.d/99_auditd.rules"
  notify: update auditd
  when:
      - SEC_ID_ENSURE_SUDO_COMMANDS_COLLECTED not in disabled_cis_rules
      - linuxcis_level2
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.15

- name: "{{ SEC_ID_ENSURE_AUDIT_CONFIG_IMMUTABLE }} | L2 | PATCH | Ensure the audit configuration is immutable"
  debug:
    msg: "Control being set via Handler 'update auditd' which writes to /etc/audit.d/99_auditd.rules"
  notify: update auditd
  when:
      - SEC_ID_ENSURE_AUDIT_CONFIG_IMMUTABLE not in disabled_cis_rules
      - linuxcis_level2
  tags:
      - level2-server
      - level2-workstation
      - auditd
      - patch
      - rule_4.1.17
