---

- name: "1.10 | L1 | PATCH | Ensure system-wide crypto policy is not legacy"
  shell: |
      update-crypto-policies --set "{{ linuxcis_crypto_policy }}"
      update-crypto-policies
  when:
      - SEC_ID_ENSURE_CRYPTO_POLICY_NOT_LEGACY not in disabled_cis_rules
      - system_wide_crypto_policy['stdout'] == 'LEGACY'
  tags:
      - level1-server
      - level1-workstation
      - no system_is_ec2
      - patch
      - rule_1.10


- name: "1.11 | L2 | PATCH | Ensure system-wide crypto policy is FUTURE or FIPS"
  shell: |
      update-crypto-policies --set "{{ linuxcis_crypto_policy }}"
      update-crypto-policies
  when:
      - SEC_ID_ENSURE_CRYPTO_POLICY_FUTURE_FIPS not in disabled_cis_rules
      - system_wide_crypto_policy['stdout'] not in linuxcis_allowed_crypto_policies
      - linuxcis_level2
  tags:
      - level2-server
      - level2-workstation
      - not system_is_ec2
      - patch
      - rule_1.11
