---

- name: "{{ SEC_ID_ENSURE_CRON_ENABLED }} | L1 | PATCH | Ensure cron daemon is enabled and running"
  service:
      name: crond
      enabled: yes
      state: started
  when:
      - SEC_ID_ENSURE_CRON_ENABLED not in disabled_cis_rules
  tags:
      - level1
      - patch
      - rule_5.1.1

- name: "{{ SEC_ID_ENSURE_CRONTAB_PERMISSIONS }} | L1 | PATCH | Ensure permissions on /etc/crontab are configured"
  file:
      dest: /etc/crontab
      owner: root
      group: root
      mode: 0600
  when:
      - SEC_ID_ENSURE_CRONTAB_PERMISSIONS not in disabled_cis_rules
  tags:
      - level1
      - patch
      - rule_5.1.2

- name: "{{ SEC_ID_ENSURE_CRON_HOURLY_PERMISSIONS }} | L1 | PATCH | Ensure permissions on /etc/cron.hourly are configured"
  file:
      dest: /etc/cron.hourly
      state: directory
      owner: root
      group: root
      mode: 0700
  when:
      - SEC_ID_ENSURE_CRON_HOURLY_PERMISSIONS not in disabled_cis_rules
  tags:
      - level1
      - patch
      - rule_5.1.3

- name: "{{ SEC_ID_ENSURE_CRON_DAILY_PERMISSIONS }} | L1 | PATCH | Ensure permissions on /etc/cron.daily are configured"
  file:
      dest: /etc/cron.daily
      state: directory
      owner: root
      group: root
      mode: 0700
  when:
      - SEC_ID_ENSURE_CRON_DAILY_PERMISSIONS not in disabled_cis_rules
  tags:
      - level1
      - patch
      - rule_5.1.4

- name: "{{ SEC_ID_ENSURE_CRON_WEEKLY_PERMISSIONS }} | L1 | PATCH | Ensure permissions on /etc/cron.weekly are configured"
  file:
      dest: /etc/cron.weekly
      state: directory
      owner: root
      group: root
      mode: 0700
  when:
      - SEC_ID_ENSURE_CRON_WEEKLY_PERMISSIONS not in disabled_cis_rules
  tags:
      - level1
      - patch
      - rule_5.1.5

- name: "{{ SEC_ID_ENSURE_CRON_MONTHLY_PERMISSIONS }} | L1 | PATCH | Ensure permissions on /etc/cron.monthly are configured"
  file:
      dest: /etc/cron.monthly
      state: directory
      owner: root
      group: root
      mode: 0700
  when:
      - SEC_ID_ENSURE_CRON_MONTHLY_PERMISSIONS not in disabled_cis_rules
  tags:
      - level1
      - patch
      - rule_5.1.6

- name: "{{ SEC_ID_ENSURE_CRON_D_PERMISSIONS }} | L1 | PATCH | Ensure permissions on /etc/cron.d are configured"
  file:
      dest: /etc/cron.d
      state: directory
      owner: root
      group: root
      mode: 0700
  when:
      - SEC_ID_ENSURE_CRON_D_PERMISSIONS not in disabled_cis_rules
  tags:
      - level1
      - patch
      - rule_5.1.7

- name: "{{ SEC_ID_ENSURE_CRON_RESTRICTED }} | L1 | PATCH | Ensure cron is restricted to authorized users"
  block:
      - name: "{{ SEC_ID_ENSURE_CRON_RESTRICTED }} | L1 | PATCH | Ensure cron is restricted to authorized users | Remove cron.deny"
        file:
            dest: /etc/cron.deny
            state: absent

      - name: "{{ SEC_ID_ENSURE_CRON_RESTRICTED }} | L1 | PATCH | Ensure cron is restricted to authorized users | Check if cron.allow exists"
        stat:
            path: "/etc/cron.allow"
        register: p

      - name: "{{ SEC_ID_ENSURE_CRON_RESTRICTED }} | L1 | PATCH | Ensure cron is restricted to authorized users | Ensure cron.allow is restricted to authorized users"
        file:
            dest: /etc/cron.allow
            state: '{{ "file" if  p.stat.exists else "touch" }}'
            owner: root
            group: root
            mode: 0600
  when:
      - SEC_ID_ENSURE_CRON_RESTRICTED not in disabled_cis_rules
  tags:
      - level1
      - patch
      - rule_5.1.8

- name: "{{ SEC_ID_ENSURE_AT_RESTRICTED }} | L1 | PATCH | Ensure at is restricted to authorized users"
  block:
      - name: "{{ SEC_ID_ENSURE_AT_RESTRICTED }} | L1 | PATCH | Ensure at is restricted to authorized users | Remove at.deny"
        file:
            dest: /etc/at.deny
            state: absent

      - name: "{{ SEC_ID_ENSURE_AT_RESTRICTED }} | L1 | AUDIT | Ensure at is restricted to authorized users | Check if at.allow exists"
        stat:
            path: "/etc/at.allow"
        register: p

      - name: "{{ SEC_ID_ENSURE_AT_RESTRICTED }} | L1 | PATCH | Ensure at is restricted to authorized users | Ensure at.allow is restricted to authorized users"
        file:
            dest: /etc/at.allow
            state: '{{ "file" if  p.stat.exists else "touch" }}'
            owner: root
            group: root
            mode: 0600
  when:
      - SEC_ID_ENSURE_AT_RESTRICTED not in disabled_cis_rules
  tags:
      - level1
      - patch
      - rule_5.1.9
