---

- name: "{{ SEC_ID_CREATE_CUSTOM_AUTHSELECT_PROFILE }} | L1 | PATCH | Create custom authselect profile"
  block:
      - name: "{{ SEC_ID_CREATE_CUSTOM_AUTHSELECT_PROFILE }} | L1 | PATCH | Create custom authselect profile | Gather profiles"
        shell: 'authselect current | grep "Profile ID: custom/"'
        failed_when: false
        changed_when: false
        check_mode: false
        register: linuxcis_autheselect_custom_profiles_out

      - name: "{{ SEC_ID_CREATE_CUSTOM_AUTHSELECT_PROFILE }} | L1 | AUDIT | Create custom authselect profile | Show profiles"
        debug:
            msg:
                - "Below are the current custom profiles"
                - "{{ linuxcis_autheselect_custom_profiles_out.stdout_lines }}"

      - name: "{{ SEC_ID_CREATE_CUSTOM_AUTHSELECT_PROFILE }} | L1 | PATCH | Create custom authselect profile | Create custom profiles"
        shell: authselect create-profile {{ linuxcis_authselect['custom_profile_name'] }} -b {{ linuxcis_authselect['default_file_to_copy'] }}
        when: linuxcis_authselect_custom_profile_create
  when:
      - SEC_ID_CREATE_CUSTOM_AUTHSELECT_PROFILE not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - patch
      - authselect
      - rule_5.3.1

- name: "{{ SEC_ID_SELECT_AUTHSELECT_PROFILE }} | L1 | PATCH | Select authselect profile"
  block:
      - name: "{{ SEC_ID_SELECT_AUTHSELECT_PROFILE }} | L1 | AUDIT | Select authselect profile | Gather profiles and enabled features"
        shell: "authselect current"
        failed_when: false
        changed_when: false
        check_mode: false
        register: linuxcis_autheselect_profiles_out

      - name: "{{ SEC_ID_SELECT_AUTHSELECT_PROFILE }} | L1 | AUDIT | Select authselect profile | Show profiles"
        debug:
            msg:
                - "Below are the current custom profiles"
                - "{{ linuxcis_autheselect_profiles_out.stdout_lines }}"

      - name: "{{ SEC_ID_SELECT_AUTHSELECT_PROFILE }} | L1 | PATCH | Select authselect profile | Create custom profiles"
        shell: "authselect select custom/{{ linuxcis_authselect['custom_profile_name'] }} {{ linuxcis_authselect['options'] }}"
        when: linuxcis_authselect_custom_profile_select
  when:
      - SEC_ID_SELECT_AUTHSELECT_PROFILE not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - patch
      - authselect
      - rule_5.3.2

- name: "{{ SEC_ID_ENSURE_AUTHSELECT_INCLUDES_WITH_FAILLOCK }} | L1 | PATCH | Ensure authselect includes with-faillock"
  block:
      - name: "{{ SEC_ID_ENSURE_AUTHSELECT_INCLUDES_WITH_FAILLOCK }} | L1 | AUDIT | Ensure authselect includes with-faillock | Gather profiles and enabled features"
        shell: "authselect current | grep with-faillock"
        failed_when: false
        changed_when: false
        check_mode: false
        register: linuxcis_autheselect_faillock_profiles_out

      - name: "{{ SEC_ID_ENSURE_AUTHSELECT_INCLUDES_WITH_FAILLOCK }} | L1 | AUDIT | Ensure authselect includes with-faillock| Show profiles"
        debug:
            msg:
                - "Below are the current custom profiles"
                - "{{ linuxcis_autheselect_faillock_profiles_out.stdout_lines }}"

      - name: "{{ SEC_ID_ENSURE_AUTHSELECT_INCLUDES_WITH_FAILLOCK }} | L1 | PATCH | Ensure authselect includes with-faillock | Create custom profiles"
        shell: "authselect select custom/{{ linuxcis_authselect['custom_profile_name'] }} with-faillock"
        when: linuxcis_authselect_custom_profile_select
  when:
      - SEC_ID_ENSURE_AUTHSELECT_INCLUDES_WITH_FAILLOCK not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - patch
      - authselect
      - rule_5.3.3
