---
# Disable/Enable whole sections (Default is for all)
linuxcis_section1: true
linuxcis_section2: true
linuxcis_section3: true
linuxcis_section4: true
linuxcis_section5: true
linuxcis_section6: true

system_is_container: false
container_vars_file: is_container.yml

# Disable all level 2 CIS rules
# Set to false to skip all level2 modifications
linuxcis_level2: true

# Disable/Enable OS check
# If Disabled, this role will run but will fail if the OS family is not supported
linuxcis_os_check: true

# Whether to skip the reboot
linuxcis_skip_reboot: true

## Python Binary - RHEL7 only
## This is used for python3 Installations where python2 OS modules are used in ansible
python2_bin: /bin/python2.7


## Benchmark name used by audting control role
# The audit variable found at the base
# TODO, does not work yet.
benchmark: RHEL7-CIS

#### Basic external goss audit enablement settings ####
#### Precise details - per setting can be found at the bottom of this file ####

### Goss is required on the remote host
setup_audit: false
# How to retrive goss
# Options are copy or download - detailed settings at the bottom of this file
# you will need to access to either github or the file already dowmloaded
get_goss_file: download

# how to get audit files onto host options
# options are git/copy/get_url
audit_content: git

# Timeout for those cmds that take longer to run where timeout set
audit_cmd_timeout: 30000

# enable audits to run - this  runs the audit and get the latest content
run_audit: false

### End Goss enablements ####
#### Detailed settings found at the end of this document ####


# Misc. environment variables
linuxcis_skip_for_travis: false
linuxcis_system_is_container: false
system_is_ec2: false

# Change to false if using EFI boot changes 1.1.1.4 to stop vfat
linuxcis_legacy_boot: true

# These two variables can contain the CIS sections you want to disable from this role.

# In this list, you need to put the explicit section number in string form. e.g. ['1.1.1', '5.3']
# Any section in this list will be skipped. However if your infrastructure contains multiple distributions
# going by the section ID will disable different sections in each distribution
# in that case, use instead disabled_cis_sections below.
disabled_cis_rules: []
# In this list, you need to put the section ID which you want to disable.
# For example ['SEC_ID_CONFIGURE_PAM', 'SEC_ID_FIREWALL_CONFIGURATION']
# Any section here will be translated to the relevant section number depending on the distribution
# and appended into disabled_cis_rules.
# Thus all sections specified in this list will be applier or considered for CIS benchmarks.
disabled_cis_sections: []

# Service configuration booleans set true to keep service
linuxcis_avahi_server: false
linuxcis_cups_server: false
linuxcis_dhcp_server: false
linuxcis_ldap_server: false
linuxcis_telnet_server: false
linuxcis_nfs_server: false
linuxcis_rpc_server: false
linuxcis_ntalk_server: false
linuxcis_rsyncd_server: false
linuxcis_tftp_server: false
linuxcis_rsh_server: false
linuxcis_nis_server: false
linuxcis_snmp_server: false
linuxcis_squid_server: false
linuxcis_smb_server: false
linuxcis_dovecot_server: false
linuxcis_httpd_server: false
linuxcis_vsftpd_server: false
linuxcis_named_server: false
linuxcis_nfs_rpc_server: false
linuxcis_is_mail_server: false
linuxcis_bind: false
linuxcis_vsftpd: false
linuxcis_httpd: false
linuxcis_dovecot: false
linuxcis_samba: false
linuxcis_squid: false
linuxcis_net_snmp: false
linuxcis_allow_autofs: false

## Section 1 vars

# SEC_ID_CONFIGURE_TMP
# These settings go into the /etc/fstab file for the /tmp mount settings
# The value must contain nosuid,nodev,noexec to conform to CIS standards
# linuxcis_tmp_tmpfs_settings: "defaults,rw,nosuid,nodev,noexec,relatime 0 0"
# If set true uses the tmp.mount service else using fstab configuration
linuxcis_tmp_svc: false

# SEC_ID_ENSURE_RHSM_CONFIGURED
# This is the login information for your RedHat Subscription
# DO NOT USE PLAIN TEXT PASSWORDS!!!!!
# The intent here is to use a password utility like Ansible Vault here
rhel8cis_rh_sub_user: user
rhel8cis_rh_sub_password: password

# SEC_ID_CONFIGURE_SUDO
linuxcis_varlog_location: "/var/log/sudo.log"

# xinetd required
linuxcis_xinetd_required: false

# RedHat Satellite Subscription items
linuxcis_rhnsd_required: false

# SEC_ID_BOOT_PASSWORD
linuxcis_set_boot_pass: false
linuxcis_bootloader_password_hash: 'grub.pbkdf2.sha512.changethispart'
linuxcis_bootloader_password: random

# System network parameters (host only OR host and router)
linuxcis_is_router: false

# IPv6 required
linuxcis_ipv6_required: true

# AIDE
linuxcis_config_aide: true
# AIDE cron settings
linuxcis_aide_cron:
    cron_user: root
    cron_file: /etc/cron.d/aide.cron
    # Default dependent in each distro.
    # Provide your own to override
    # aide_job: '/usr/sbin/aide --check'
    aide_minute: 0
    aide_hour: 5
    aide_day: '*'
    aide_month: '*'
    aide_weekday: '*'


# SEC_ID_MANDATORY_ACCESS_CONTROL
# Enable/Disable SELinux or AppArmor
linuxcis_mandatory_access_control_disable: false
# SEC_ID_ENSURE_SELINUX_POLICY_CONFIGURED
# Only for CIS for Red Hat family
# For 8+, this is expected to always be enforcing
linuxcis_selinux_state: enforcing
# SEC_ID_ENSURE_SELINUX_POLICY_CONFIGURED
# SELinux policy
linuxcis_selinux_pol: targeted

# Whether or not to run tasks related to auditing/patching the desktop environment
linuxcis_gui: no

# SEC_ID_ENSURE_CRYPTO_POLICY_NOT_LEGACY / SEC_ID_ENSURE_CRYPTO_POLICY_FUTURE_FIPS
# Set crypto policy (LEGACY, DEFAULT, FUTURE, FIPS)
# Control 1.10 sates not ot use LEGACY and control 1.11 says to use FUTURE or FIPS.
linuxcis_crypto_policy: "FUTURE"

# Set to 'true' if X Windows is needed in your environment
linuxcis_xwindows_required: no


# Warning Banner Content (issue, issue.net, motd)
linuxcis_warning_banner: |
    Authorized uses only. All activity may be monitored and reported.
# End Banner

# Section 2 Control Variables

linuxcis_openldap_clients_required: false
linuxcis_telnet_required: false
linuxcis_talk_required: false
linuxcis_rsh_required: false
linuxcis_ypbind_required: false

# Time Synchronization - Either chrony or ntp
linuxcis_time_synchronization: chrony

linuxcis_time_synchronization_servers:
    - 0.pool.ntp.org
    - 1.pool.ntp.org
    - 2.pool.ntp.org
    - 3.pool.ntp.org

debiancis_ntp_server_list: "0.debian.pool.ntp.org 1.debian.pool.ntp.org"
debiancis_ntp_fallback_server_list: "2.debian.pool.ntp.org 3.debian.pool.ntp.org"
# debiancis_chrony_user is the user that chrony will use, default is _chrony
debiancis_chrony_user: "_chrony"

linuxcis_chrony_server_options: "minpoll 8"
linuxcis_ntp_server_options: "iburst"

# Section 3 Control Variables

# SEC_ID_ENSURE_WIRELESS_INTERFACES_DISABLED
# ubtu20cis_install_network_manager determines if this role can install network manager on Ubuntu Deployents
debiancis_install_network_manager: true

# Firewall Service for RedHat - either firewalld, nftables or iptables
redhatcis_firewall: firewalld
# Firewall Service for Ubuntu - either ufw, nftables or iptables
debiancis_firewall: iptables
linuxcis_default_zone: public

# Used for CIS validation via goss
# see ansible_vars_goss.yml.j2
linuxcis_firewall_services:
    - ssh
    - dhcpv6-client

# SEC_ID_ENSURE_UFW_OUTBOUND_AND_ESTABLISHED_CONNECTION_CONFIGURED
# debiancis_ufw_allow_out_ports are the ports for the firewall to allow
# if you want to allow out on all ports set variable to "all", example debiancis_ufw_allow_out_ports: "all"
debiancis_ufw_allow_out_ports:
    - 53
    - 80
    - 443

# SEC_ID_CONFIGURE_NFTABLES
# not tested but added example for clarity - This will break connections
# If the tables dont exist automatically create the tablename below
linuxcis_nft_tables_autoNewTable: false
# create chain if doesnt exist
linuxcis_nft_tables_autoChainCreate: false
# create a table called
linuxcis_nft_tables_tableName: filter

## Section4 vars

# auditd settings
linuxcis_auditd:
    space_left_action: email
    action_mail_acct: root
    admin_space_left_action: halt
    max_log_file_action: keep_logs

linuxcis_logrotate: "daily"

# SEC_ID_ENSURE_AUDIT_BACKLOG_LIMIT_SUFFICIENT
# linuxcis_audit_backlog_limit value needs to be 8192 or larger to conform to CIS standards
linuxcis_audit_backlog_limit: 8192

# The max_log_file parameter should be based on your sites policy
linuxcis_max_log_file_size: 10

# SEC_ID_ENSURE_AUDIT_BACKLOG_LIMIT_SUFFICIENT/SEC_ID_ENSURE_RSYSLOG_REMOTE_LOGGING
# remote and destation log server name
linuxcis_remote_log_server: logagg.example.com

# SEC_ID_ENSURE_RSYSLOG_REMOTE_LOGGING
linuxcis_system_is_log_server: false
# SEC_ID_ENSURE_RSYSLOG_INSTALLED
# Syslog system - either rsyslog or syslog-ng
linuxcis_syslog: rsyslog
# SEC_ID_ENSURE_LOGGING_CONFIGURED
linuxcis_rsyslog_ansiblemanaged: true

# SEC_ID_ENSURE_LOGROTATE_CONFIGURED - Used in Debian CIS only
# linuxcis_logrotate_create_settings are the settings for the create parameter in /etc/logrotate.conf
# The permissions need to be 640 or more restrictive.
# If you would like to include user/group settings to this parameter format the var as below
# linuxcis_logrotate_create_settings: "0640 root utmp"
linuxcis_logrotate_create_settings: "0640"

## Section5 vars

# SEC_ID_CONFIGURE_SSH
# SSH variables
linuxcis_ssh_loglevel: INFO
linuxcis_ssh_maxsessions: 4
linuxcis_inactivelock:
    lock_days: 30
linuxcis_sshd:
    clientalivecountmax: 3
    clientaliveinterval: 300
    ciphers: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
    macs: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256"
    kex: "curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256"
    logingracetime: 60
    # WARNING: make sure you understand the precedence when working with these values!!
    # allowusers:
    # allowgroups: systems dba
    # denyusers:
    # denygroups:


# SEC_ID_CONFIGURE_PAM
# pam variables
linuxcis_pam_faillock:
    attempts: 5
    interval: 900
    unlock_time: 900
    fail_for_root: no
    remember: 5
    pwhash: sha512
# SEC_ID_ENSURE_PASSWORD_CREATION_REQS
linuxcis_pam_password:
    minlen: "14"
    minclass: "4"

# SEC_ID_ENSURE_SUDO_INSTALLED - For Debian CIS Only
# debiancis_sudo_package is the name of the sudo package to install
# The possible values are "sudo" or "sudo-ldap"
debiancis_sudo_package: "sudo"

# SEC_ID_CONFIGURE_AUTHSELECT - RHEL8+ only
# Custom authselect profile settings.
# Settings in place now will fail, they are place holders from the control example
# Due to the way many multiple options and ways to configure this control needs to be enabled and settings adjusted to minimise risk
linuxcis_use_authconfig: false
linuxcis_authselect:
    custom_profile_name: custom-profile
    default_file_to_copy: "sssd --symlink-meta"
    options: with-sudo with-faillock without-nullok
# SEC_ID_CREATE_CUSTOM_AUTHSELECT_PROFILE
# Enable automation to create custom profile settings, using the settings above
linuxcis_authselect_custom_profile_create: false
# SEC_ID_SELECT_AUTHSELECT_PROFILE
# Enable automation to select custom profile options, using the settings above
linuxcis_authselect_custom_profile_select: false

# SEC_ID_SET_SHADOW_SUITE_PARAMETERS
linuxcis_pass:
    max_days: 90
    min_days: 7
    warn_age: 7
# SEC_ID_ENSURE_PASSWORD_CHANGE_IN_PAST
linuxcis_futurepwchgdate_autofix: true

# SEC_ID_CONFIGURE_USER_ACCOUNTS_ENVIRONMENT
# UID settings for interactive users
# These are used in 99_auditd.rules as well
min_int_uid: 1000
max_int_uid: 65533
# SEC_ID_ENSURE_DEFAULT_USER_SHELL_TIMEOUT
# Session timeout setting file (TMOUT setting can be set in multiple files)
# Timeout value is in seconds. (60 seconds * 10 = 600)
linuxcis_shell_session_timeout:
    file: /etc/profile.d/tmout.sh
    timeout: 600


# SEC_ID_CONFIGURE_SUDO
# Group to be used for su
# this group needs to exists groups will not be created for remediation this is considered sys admins

# linuxcis_sugroup: sugroup

# SEC_ID_ENSURE_SU_COMMAND_RESTRICTED
# wheel users list
linuxcis_sugroup_users: "root"

## Section6 vars

# SEC_ID_AUDIT_SYSTEM_FILE_PERMISSIONS
linuxcis_rpm_audit_file: /var/tmp/rpm_file_check

# SEC_ID_ENSURE_NO_WORLD_WRITABLE_FILES
# Allow ansible to adjust world-writable files.
# False will just display world-writable files, True will remove world-writable
linuxcis_no_world_write_adjust: true
# SEC_ID_ENSURE_USERS_OWN_HOMEDIRS
linuxcis_passwd_label: "{{ (this_item | default(item)).id }}: {{ (this_item | default(item)).dir }}"
# SEC_ID_ENSURE_USERS_DOTFILE_PERMS
linuxcis_dotperm_ansiblemanaged: true

#### Goss Configuration Settings ####

### Goss binary settings ###
goss_version:
    release: v0.3.16
    checksum: 'sha256:827e354b48f93bce933f5efcd1f00dc82569c42a179cf2d384b040d8a80bfbfb'
audit_bin_path: /usr/local/bin/
audit_bin: "{{ audit_bin_path }}goss"
audit_format: json

# if get_goss_file == download change accordingly
goss_url: "https://github.com/aelsabbahy/goss/releases/download/{{ goss_version.release }}/goss-linux-amd64"

## if get_goss_file - copy the following needs to be updated for your environment
## it is expected that it will be copied from somewhere accessible to the control node
## e.g copy from ansible control node to remote host
copy_goss_from_path: /some/accessible/path

### Goss Audit Benchmark file ###
## managed by the control audit_content
# git
audit_file_git: "https://github.com/db0/{{ benchmark }}-Audit.git"
audit_git_version: main

# copy:
audit_local_copy: "some path to copy from"

# get_url:
audit_files_url: "some url maybe s3?"

# Where the goss audit configuration will be stored
audit_files: "/var/tmp/{{ benchmark }}-Audit/"

## Goss configuration information
# Where the goss configs and outputs are stored
audit_out_dir: '/var/tmp'
audit_conf_dir: "{{ audit_out_dir }}/{{ benchmark }}-Audit/"
pre_audit_outfile: "{{ audit_out_dir }}/{{ ansible_hostname }}_pre_scan_{{ ansible_date_time.epoch }}.{{ audit_format }}"
post_audit_outfile: "{{ audit_out_dir }}/{{ ansible_hostname }}_post_scan_{{ ansible_date_time.epoch }}.{{ audit_format }}"

## The following should not need changing
goss_file: "{{ audit_conf_dir }}goss.yml"
audit_vars_path: "{{ audit_conf_dir  }}/vars/{{ ansible_hostname }}.yml"
audit_results: |
      The pre remediation results are: {{ pre_audit_summary }}.
      The post remediation results are: {{ post_audit_summary }}.
      Full breakdown can be found in {{ audit_out_dir }}
