---

- name: "{{ SEC_ID_ENSURE_SETROUBLESHOOT_NOT_INSTALLED }} | {{ cis_level }} | PATCH | Ensure SETroubleshoot is not installed"
  package:
      name: "{{ SETROUBLESHOOT_PKG }}"
      state: absent
  tags: always
