---

- name: "{{ SEC_ID_ENSURE_SELINUX_POLICY_CONFIGURED }} | {{ cis_level }} | PATCH | Ensure SELinux policy is configured\n
         {{ SEC_ID_ENSURE_SELINUX_MODE_ENFORCING_OR_PERMISSIVE }} | {{ cis_level }} | PATCH | Ensure the SELinux state is enforcing or permissive"
  selinux:
      conf: /etc/selinux/config
      policy: "{{ linuxcis_selinux_pol }}"
      state: "{{ linuxcis_selinux_state }}"
  tags: always
