---
- name: "{{ SEC_ID_ENSURE_APPARMOR_INSTALLED }} | L1 | PATCH | Ensure AppArmor is installed"
  apt:
      name:
      - apparmor
      - apparmor-utils
      state: present
  when:
      - SEC_ID_ENSURE_APPARMOR_INSTALLED not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.6.1.1
      - apparmor

- name: "{{ SEC_ID_ENSURE_APPARMOR_NOT_DISABLED_IN_BOOTLOADER }} | L1 | PATCH | Ensure AppArmor is enabled in the bootloader configuration"
  block:
      - name: "{{ SEC_ID_ENSURE_APPARMOR_NOT_DISABLED_IN_BOOTLOADER }} | L1 | AUDIT | Ensure AppArmor is enabled in the bootloader configuration | Get current settings"
        shell: grep "GRUB_CMDLINE_LINUX=" /etc/default/grub | cut -f2 -d'"'
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu20cis_1_6_1_2_cmdline_settings

      - name: "{{ SEC_ID_ENSURE_APPARMOR_NOT_DISABLED_IN_BOOTLOADER }} | L1 | PATCH | Ensure AppArmor is enabled in the bootloader configuration | Set apparmor settings if none exist"
        lineinfile:
            path: /etc/default/grub
            regexp: '^GRUB_CMDLINE_LINUX'
            line: 'GRUB_CMDLINE_LINUX="apparmor=1 security=apparmor {{ ubtu20cis_1_6_1_2_cmdline_settings.stdout }}"'
            insertafter: '^GRUB_'
        when:
            - "'apparmor' not in ubtu20cis_1_6_1_2_cmdline_settings.stdout"
            - "'security' not in ubtu20cis_1_6_1_2_cmdline_settings.stdout"
        notify: grub update

      - name: "{{ SEC_ID_ENSURE_APPARMOR_NOT_DISABLED_IN_BOOTLOADER }} | L1 | PATCH | Ensure AppArmor is enabled in the bootloader configuration | Set apparmor settings if none exist | Replace apparmor settings when exists"
        replace:
            path: /etc/default/grub
            regexp: "{{ item.regexp }}"
            replace: "{{ item.replace }}"
        with_items:
            - { regexp: 'apparmor=\S+', replace: 'apparmor=1' }
            - { regexp: 'security=\S+', replace: 'security=apparmor' }
        when:
            - "'apparmor' in ubtu20cis_1_6_1_2_cmdline_settings.stdout"
            - "'security' in ubtu20cis_1_6_1_2_cmdline_settings.stdout"
        notify: grub update
  when:
      - SEC_ID_ENSURE_APPARMOR_NOT_DISABLED_IN_BOOTLOADER not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.6.1.2
      - apparmor

- name: "{{ SEC_ID_ENSURE_APPARMOR_MODE_ENFORCING_OR_COMPLAIN }} | L1 | PATCH | Ensure all AppArmor Profiles are in enforce or complain mode"
  command: aa-enforce /etc/apparmor.d/*
  failed_when: false
  when:
      - SEC_ID_ENSURE_APPARMOR_MODE_ENFORCING_OR_COMPLAIN not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.6.1.3
      - apparmor

- name: "{{ SEC_ID_ENSURE_APPARMOR_MODE_ENFORCING }} | L2 | PATCH | Ensure all AppArmor Profiles are enforcing"
  command: aa-enforce /etc/apparmor.d/*
  failed_when: false
  when:
      - SEC_ID_ENSURE_APPARMOR_MODE_ENFORCING not in disabled_cis_rules
  tags:
      - level2-server
      - level2-workstation
      - automated
      - scored
      - patch
      - rule_1.6.1.4
      - apparmor
