---
- name: "{{ SEC_ID_ENSURE_IP_FORWARDING_DISABLED }} | L1 | PATCH | Ensure IP forwarding is disabled | IPv4"
  block:
      - name: "{{ SEC_ID_ENSURE_IP_FORWARDING_DISABLED }} | L1 | PATCH | Ensure IP forwarding is disabled | IPv4"
        debug:
            msg: "Control being set via Handler 'update sysctl' which writes to /etc/sysctl.d/99-sysctl.conf"
        notify:
            - update sysctl
            - sysctl flush ipv4 route table

      - name: "{{ SEC_ID_ENSURE_IP_FORWARDING_DISABLED }} | L1 | PATCH | Ensure IP forwarding is disabled IPv6"
        debug:
            msg: "Control being set via Handler 'update sysctl' which writes to /etc/sysctl.d/99-sysctl.conf"
        notify:
            - sysctl flush ipv6 route table
            - update sysctl
        when:
            - linuxcis_ipv6_required
  when:
      - not linuxcis_is_router
      - SEC_ID_ENSURE_IP_FORWARDING_DISABLED not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - sysctl
      - patch
      - rule_3.2.1

- name: "{{ SEC_ID_ENSURE_PACKET_REDIRECT_DISABLED }} | L1 | PATCH | Ensure packet redirect sending is disabled"
  debug:
      msg: "Control being set via Handler 'update sysctl' which writes to /etc/sysctl.d/99-sysctl.conf"
  notify:
      - update sysctl
      - sysctl flush ipv4 route table
  when:
      - not linuxcis_is_router
      - SEC_ID_ENSURE_PACKET_REDIRECT_DISABLED not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - sysctl
      - patch
      - rule_3.2.2
