---

- name: "{{ SEC_ID_ENSURE_DISABLE_IPV6 }} | L2 | PATCH | Disable IPv6"
  replace:
      dest: /etc/default/grub
      regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!ipv6.disable=1)(?:")'
      replace: '\1"\2 ipv6.disable=1"'
      follow: true
  notify: grub2cfg
  when:
      - not linuxcis_ipv6_required
      - SEC_ID_ENSURE_DISABLE_IPV6 not in disabled_cis_rules
      - linuxcis_level2
  tags:
      - level2-server
      - level2-workstation
      - patch
      - rule_3.6
