---

- name: "{{ SEC_ID_ENSURE_SUDO_INSTALLED }} | L1 | PATCH | Ensure sudo is installed"
  package:
      name: sudo
      state: present
  become: true
  when:
      - SEC_ID_ENSURE_SUDO_INSTALLED not in disabled_cis_rules
  tags:
      - level1
      - sudo
      - patch
      - rule_5.2.1
#   vars:
#       ansible_python_interpreter: /bin/python

- name: "{{ SEC_ID_ENSURE_SUDO_PTY }} | L1 | AUDIT | Ensure sudo commands use pty"
  lineinfile:
      dest: /etc/sudoers
      regexp: '^Defaults    use_pty'
      line: 'Defaults    use_pty'
      state: present
      validate: '/usr/sbin/visudo -cf %s'
  become: true
  when:
      - SEC_ID_ENSURE_SUDO_PTY not in disabled_cis_rules
  tags:
      - level1
      - patch
      - rule_5.2.2

- name: "{{ SEC_ID_ENSURE_SUDO_LOG_EXISTS }} | L1 | PATCH | Ensure sudo log file exists"
  lineinfile:
      dest: /etc/sudoers
      regexp: '^Defaults    logfile="{{ linuxcis_varlog_location }}"'
      line: 'Defaults    logfile="{{ linuxcis_varlog_location }}"'
      state: present
      validate: '/usr/sbin/visudo -cf %s'
  become: true
  when:
      - SEC_ID_ENSURE_SUDO_LOG_EXISTS not in disabled_cis_rules
  tags:
      - level1
      - patch
      - rule_5.2.3
