---

- name: "{{ SEC_ID_ENSURE_SUDO_INSTALLED }} | L1 | PATCH | Ensure sudo is installed"
  package:
      name: "{{ SUDO_PKG }}"
      state: present
  when:
      - SEC_ID_ENSURE_SUDO_INSTALLED not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - scored
      - sudo
      - patch
      - rule_1.3.1

- name: "{{ SEC_ID_ENSURE_SUDO_PTY }} | L1 | AUDIT | Ensure sudo commands use pty"
  lineinfile:
      dest: /etc/sudoers
      regexp: '^Defaults    use_'
      line: 'Defaults    use_pty'
      insertafter: '^Defaults'
      state: present
      validate: '/usr/sbin/visudo -cf %s'
  when:
      - SEC_ID_ENSURE_SUDO_PTY not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.3.2

- name: "{{ SEC_ID_ENSURE_SUDO_LOG_EXISTS }} | L1 | PATCH | Ensure sudo log file exists"
  lineinfile:
      dest: /etc/sudoers
      regexp: '^Defaults    logfile'
      line: 'Defaults    logfile="{{ linuxcis_varlog_location }}"'
      insertafter: '^Defaults'
      state: present
      validate: '/usr/sbin/visudo -cf %s'
  when:
      - SEC_ID_ENSURE_SUDO_LOG_EXISTS not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.3.3
