---

- name: "{{ SEC_ID_BOOTLOADER_PERMS }} | L1 | PATCH | Ensure permissions on bootloader config are configured"
  copy:
      dest: "{{ UEFI_BOOTLOADER_PATH }}user.cfg"
      content: "GRUB2_PASSWORD={{ linuxcis_bootloader_password_hash }}"
      owner: root
      group: root
      mode: "{% if linuxcis_legacy_boot %}0600{% else %}0700{% endif %}"
  notify: "{{ GRUB_RECONFIG_HANDLER }}"
  tags: always
