---

- debug:
    var: grub_cfg.stat

- name: "{{ SEC_ID_BOOTLOADER_PERMS }} | L1 | PATCH | Ensure permissions on bootloader config are configured | Update grub config settings"
  file:
      path: "{{ grub_cfg.stat.source }}"
      owner: root
      group: root
      mode: 0600
  when:
      - linuxcis_legacy_boot
  tags: always

- name: "{{ SEC_ID_BOOTLOADER_PERMS }} | L1 | PATCH | Ensure permissions on bootloader config are configured | UEFI"
  mount:
      name: /boot/efi
      src: "UUID={{ item.uuid }}"
      fstype: vfat
      state: present
      opts: defaults,umask=0027,fmask=0077,uid=0,gid=0
      passno: '0'
  loop: "{{ ansible_mounts }}"
  when:
      - not linuxcis_legacy_boot
      - item.mount == "/boot/efi"
  tags: always
