---

- name: "SECTION | {{ SEC_ID_SECURE_BOOT_SETTINGS }} | Distribution Specific Order"
  include_tasks: "{{ lookup('first_found', dist_tasks) }}"
  vars:
    dist_tasks:
      - "secure_boot_settings_{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}.yml"
      - "secure_boot_settings_{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
      - "secure_boot_settings_{{ ansible_facts.distribution }}.yml"
      - "secure_boot_settings_{{ ansible_facts.os_family }}.yml"
