---

- name: "{{ SEC_ID_ENSURE_BOOTLOADER_PERMISSIONS_NOT_OVERRIDEN }} | L1 | PATCH | Ensure permissions on bootloader config are not overridden"
  block:
      - name: "{{ SEC_ID_ENSURE_BOOTLOADER_PERMISSIONS_NOT_OVERRIDEN }} | L1 | PATCH | Ensure permissions on bootloader config are not overridden | Change chmod setting"
        replace:
            path: /usr/sbin/grub-mkconfig
            regexp: 'chmod\s\d\d\d\s\${grub_cfg}.new'
            replace: 'chmod 400 ${grub_cfg}.new'

      - name: "{{ SEC_ID_ENSURE_BOOTLOADER_PERMISSIONS_NOT_OVERRIDEN }} | L1 | PATCH | Ensure permissions on bootloader config are not overridden | Remove check on password"
        lineinfile:
            path: /usr/sbin/grub-mkconfig
            regexp: 'if \[ \"x\$\{grub_cfg\}\" != "x" \] && ! grep "\^password" \${grub_cfg}.new'
            line: if [ "x${grub_cfg}" != "x" ]; then
  when:
      - SEC_ID_ENSURE_BOOTLOADER_PERMISSIONS_NOT_OVERRIDEN not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.4.1
      - grub


- name: "{{ SEC_ID_BOOT_PASSWORD }} | L1 | PATCH | Ensure bootloader password is set"
  include_tasks: "ensure_bootloader_password_set.yml"
  when:
      - linuxcis_set_boot_pass
      - SEC_ID_BOOT_PASSWORD not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - scored
      - grub
      - patch
      - rule_1.4.1

- name: "{{ SEC_ID_BOOTLOADER_PERMS }} | L1 | PATCH | Ensure permissions on bootloader config are configured"
  include_tasks: "{{ lookup('first_found', dist_tasks) }}"
  vars:
    dist_tasks:
      - "ensure_bootloader_configured_{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}.yml"
      - "ensure_bootloader_configured_{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
      - "ensure_bootloader_configured_{{ ansible_facts.distribution }}.yml"
      - "ensure_bootloader_configured_{{ ansible_facts.os_family }}.yml"
  when:
      - SEC_ID_BOOTLOADER_PERMS not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - scored
      - grub
      - patch
      - rule_1.4.2

- name: "{{ SEC_ID_SINGLE_USER_AUTH_NEEDED }} | L1 | PATCH | Ensure authentication required for single user mode"
  block:
      - name: "{{ SEC_ID_SINGLE_USER_AUTH_NEEDED }} | L1 | PATCH | Ensure authentication required for single user mode | Emergency service"
        lineinfile:
            dest: /usr/lib/systemd/system/emergency.service
            regexp: '/sbin/systemd-sulogin-shell'
            line: 'ExecStart=-/bin/sh -c "/sbin/systemd-sulogin-shell; /usr/bin/systemctl --fail --no-block default"'

      - name: "{{ SEC_ID_SINGLE_USER_AUTH_NEEDED }} | L1 | PATCH | Ensure authentication required for single user mode | Rescue service"
        lineinfile:
            dest: /usr/lib/systemd/system/rescue.service
            regexp: '/sbin/systemd-sulogin-shell'
            line: 'ExecStart=-/bin/sh -c "/sbin/systemd-sulogin-shell; /usr/bin/systemctl --fail --no-block default"'
  when:
      - SEC_ID_SINGLE_USER_AUTH_NEEDED not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_1.4.3
