---

- name: "{{ SEC_ID_ENSURE_RHSM_CONFIGURED }} | L1 | PATCH | Ensure Red Hat Subscription Manager connection is configured"
  redhat_subscription:
      state: present
      username: "{{ rhel8cis_rh_sub_user }}"
      password: "{{ rhel8cis_rh_sub_password }}"
      auto_attach: true
      no_log: true
  when:
      - ansible_distribution == "RedHat"
      - rhel8cis_rhnsd_required
      - rhel8cis_rule_1_2_1
  tags:
      - level1-server
      - level1-workstation
      - notscored
      - patch
      - rule_1.2.1
      - skip_ansible_lint  # Added as no_log still errors on ansuible-lint

- name: "{{ SEC_ID_DISABLE_RHNSD_DAEMON }} | L1 | PATCH | Disable the rhnsd Daemon"
  service:
      name: rhnsd
      state: stopped
      enabled: no
      masked: true
  when:
      - ansible_distribution == "RedHat"
      - rhnsd_service_status.stdout == "loaded" and not rhel8cis_rhnsd_required
      - rhel8cis_rule_1_2_2
  tags:
      - level1-server
      - level1-workstation
      - notscored
      - patch
      - rule_1.2.2
