---

- name: "{{ SEC_ID_CONFIGURE_GPG_KEYS }} | L1 | AUDIT | Ensure GPG keys are configured"
  shell: gpg --quiet --with-fingerprint "{{ RPM_GPG_KEY_FILE }}"
  args:
      warn: false
  when:
      - SEC_ID_CONFIGURE_GPG_KEYS not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - notscored
      - patch
      - rule_1.2.1

- name: "{{ SEC_ID_ACTIVATE_GPG_GLOBALLY }} | L1 | PATCH | Ensure gpgcheck is globally activated"
  block:
      - name: "{{ SEC_ID_ACTIVATE_GPG_GLOBALLY }} | L1 | AUDIT | Ensure gpgcheck is globally activated"
        find:
            paths: /etc/yum.repos.d
            patterns: "*.repo"
        register: yum_repos
        changed_when: false

      - name: "{{ SEC_ID_ACTIVATE_GPG_GLOBALLY }} | L1 | PATCH | Ensure gpgcheck is globally activated"
        replace:
            path: "{{ item.path }}"
            regexp: "^gpgcheck=0"
            replace: "gpgcheck=1"
        loop: "{{ yum_repos.files }}"
        loop_control:
            label: "{{ item.path }}"
  when:
      - SEC_ID_ACTIVATE_GPG_GLOBALLY not in disabled_cis_rules
  tags:
      - level1
      - patch
      - rule_1.2.3

- name: "{{ SEC_ID_CONFIGURE_PACKAGE_MANAGER_REPOS }} | L1 | AUDIT | Ensure package manager repositories are configured"
  block:
      - name: "{{ SEC_ID_CONFIGURE_GPG_KEYS }} | L1 | AUDIT | Ensure package manager repositories are configured"
        shell: yum repolist
        changed_when: false
        register: repolist
        tags:
            - skip_ansible_lint

      - name: "{{ SEC_ID_CONFIGURE_GPG_KEYS }} | L1 | AUDIT | Ensure package manager repositories are configured"
        debug:
            msg:
                - "Please check against site policy repos listed below match expected:"
                - "{{ repolist.stdout_lines }}"
  when:
      - SEC_ID_CONFIGURE_PACKAGE_MANAGER_REPOS not in disabled_cis_rules
  tags:
      - level1
      - audit
      - rule_1.2.2
      - skip_ansible_lint
