---

- name: "SECTION | {{ SEC_ID_CONFIGURE_SOFTWARE_UPDATES }} | Distribution Specific Order"
  include_tasks: "{{ lookup('first_found', dist_tasks) }}"
  vars:
    dist_tasks:
      - "configure_software_updates_{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}.yml"
      - "configure_software_updates_{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
      - "configure_software_updates_{{ ansible_facts.distribution }}.yml"
      - "configure_software_updates_{{ ansible_facts.os_family }}.yml"
