---

- name: "PREREQ | Check required packages installed | Python"
  package:
      list: "{{ item }}"
      state: present
  loop:
      - rpm-python
      - libselinux-python
      - python3
  when: ansible_python.version.major == 2
