---

- name: "{{ SEC_ID_DISABLE_IPV6 }} | L2 | PATCH | Disable IPv6 | grub"
  replace:
      dest: /etc/default/grub
      regexp: '(^GRUB_CMDLINE_LINUX\s*\=\s*)(?:")(.+)(?<!ipv6.disable=1)(?:")'
      replace: '\1"\2 ipv6.disable=1"'
  notify: grub2cfg
  when:
      - not linuxcis_ipv6_required
      - SEC_ID_DISABLE_IPV6 not in disabled_cis_rules
      - linuxcis_level2
  tags:
      - level2
      - rule_3.1.1
      - patch

- name: "{{ SEC_ID_ENSURE_WIRELESS_INTERFACE_DISABLED }} | L1 | Ensure wireless interfaces are disabled"
  block:

      - name: "{{ SEC_ID_ENSURE_WIRELESS_INTERFACE_DISABLED }} | L1 | PATCH | Ensure wireless interfaces are disabled | Check if wifi is enabled"
        shell: nmcli radio wifi
        register: rhel_07_wifi_enabled
        check_mode: false
        changed_when: rhel_07_wifi_enabled.stdout != "disabled"

      - name: "{{ SEC_ID_ENSURE_WIRELESS_INTERFACE_DISABLED }} | L1 | PATCH | Ensure wireless interfaces are disabled | Disable wifi if enabled"
        command: nmcli radio wifi off
        when: rhel_07_wifi_enabled is changed

  when:
      - SEC_ID_ENSURE_WIRELESS_INTERFACE_DISABLED not in disabled_cis_rules
      - "'NetworkManager' in ansible_facts.packages"
  tags:
      - level1
      - rule_3.1.2
