---
- name: "{{ SEC_ID_ENSURE_SOURCE_ROUTED_PACKETS_NOT_ACCEPTED }} | L1 | PATCH | Ensure source routed packets are not accepted"
  block:
      - name: "{{ SEC_ID_ENSURE_SOURCE_ROUTED_PACKETS_NOT_ACCEPTED }} | L1 | PATCH | Ensure source routed packets are not accepted | IPv4"
        debug:
            msg: "Control being set via Handler 'update sysctl' which writes to /etc/sysctl.d/99-sysctl.conf"
        notify:
            - update sysctl
            - sysctl flush ipv4 route table

      - name: "{{ SEC_ID_ENSURE_SOURCE_ROUTED_PACKETS_NOT_ACCEPTED }} | L1 | PATCH | Ensure source routed packets are not accepted | IPv6"
        debug:
            msg: "Control being set via Handler 'update sysctl' which writes to /etc/sysctl.d/99-sysctl.conf"
        notify:
            - sysctl flush ipv6 route table
            - update sysctl
        when:
            - linuxcis_ipv6_required
  when:
      - SEC_ID_ENSURE_SOURCE_ROUTED_PACKETS_NOT_ACCEPTED not in disabled_cis_rules
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.3.1

- name: "{{ SEC_ID_ENSURE_ICMP_REDIRECTS_NOT_ACCEPTED }} | L1 | PATCH | Ensure ICMP redirects are not accepted"
  block:
      - name: "{{ SEC_ID_ENSURE_ICMP_REDIRECTS_NOT_ACCEPTED }} | L1 | PATCH | Ensure ICMP redirects are not accepted | IPv4"
        debug:
            msg: "Control being set via Handler 'update sysctl' which writes to /etc/sysctl.d/99-sysctl.conf"
        notify:
            - update sysctl
            - sysctl flush ipv4 route table

      - name: "{{ SEC_ID_ENSURE_ICMP_REDIRECTS_NOT_ACCEPTED }} | L1 | PATCH | Ensure ICMP redirects are not accepted | IPv6"
        debug:
            msg: "Control being set via Handler 'update sysctl' which writes to /etc/sysctl.d/99-sysctl.conf"
        notify:
            - sysctl flush ipv6 route table
            - update sysctl
        when:
            - linuxcis_ipv6_required
  when:
      - SEC_ID_ENSURE_ICMP_REDIRECTS_NOT_ACCEPTED not in disabled_cis_rules
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.3.2

- name: "{{ SEC_ID_ENSURE_SECURE_ICMP_REDIRECTS_NOT_ACCEPTED }} | L1 | PATCH | Ensure secure ICMP redirects are not accepted"
  debug:
    msg: "Control being set via Handler 'update sysctl' which writes to /etc/sysctl.d/99-sysctl.conf"
  notify: update sysctl
  when:
      - SEC_ID_ENSURE_SECURE_ICMP_REDIRECTS_NOT_ACCEPTED not in disabled_cis_rules
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.3.3

- name: "{{ SEC_ID_ENSURE_SUSPICIOUS_PACKETS_LOGGED }} | L1 | PATCH | Ensure suspicious packets are logged"
  debug:
    msg: "Control being set via Handler 'update sysctl' which writes to /etc/sysctl.d/99-sysctl.conf"
  notify: update sysctl
  when:
      - SEC_ID_ENSURE_SUSPICIOUS_PACKETS_LOGGED not in disabled_cis_rules
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.3.4

- name: "{{ SEC_ID_ENSURE_BROADCAST_ICMP_REQUESTS_IGNORED }} | L1 | PATCH | Ensure broadcast ICMP requests are ignored"
  debug:
    msg: "Control being set via Handler 'update sysctl' which writes to /etc/sysctl.d/99-sysctl.conf"
  notify: update sysctl
  when:
      - SEC_ID_ENSURE_BROADCAST_ICMP_REQUESTS_IGNORED not in disabled_cis_rules
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.3.5

- name: "{{ SEC_ID_ENSURE_BOGUS_ICMP_RESPONSES_IGNORED }} | L1 | PATCH | Ensure bogus ICMP responses are ignored"
  debug:
    msg: "Control being set via Handler 'update sysctl' which writes to /etc/sysctl.d/99-sysctl.conf"
  notify: update sysctl
  when:
      - SEC_ID_ENSURE_BOGUS_ICMP_RESPONSES_IGNORED not in disabled_cis_rules
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.3.6

- name: "{{ SEC_ID_ENSURE_REVERSE_PATH_FILTERING_ENABLED }} | L1 | PATCH | Ensure Reverse Path Filtering is enabled"
  debug:
    msg: "Control being set via Handler 'update sysctl' which writes to /etc/sysctl.d/99-sysctl.conf"
  notify: update sysctl
  when:
      - SEC_ID_ENSURE_REVERSE_PATH_FILTERING_ENABLED not in disabled_cis_rules
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.3.7

- name: "{{ SEC_ID_ENSURE_TCP_SYN_COOKIES_ENABLED }} | L1 | PATCH | Ensure TCP SYN Cookies is enabled"
  debug:
    msg: "Control being set via Handler 'update sysctl' which writes to /etc/sysctl.d/99-sysctl.conf"
  notify: update sysctl
  when:
      - SEC_ID_ENSURE_TCP_SYN_COOKIES_ENABLED not in disabled_cis_rules
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.3.8

- name: "{{ SEC_ID_ENSURE_ROUTER_ADVERTISEMENTS_NOT_ACCEPTED }} | L1 |  PATCH | Ensure IPv6 router advertisements are not accepted"
  debug:
    msg: "Control being set via Handler 'update sysctl' which writes to /etc/sysctl.d/99-sysctl.conf"
  notify:
      - sysctl flush ipv6 route table
      - update sysctl
  when:
      - linuxcis_ipv6_required
      - SEC_ID_ENSURE_ROUTER_ADVERTISEMENTS_NOT_ACCEPTED not in disabled_cis_rules
  tags:
      - level1
      - sysctl
      - patch
      - rule_3.3.9
