---

- name: "{{ SEC_ID_ENSURE_ROOT_LOGIN_CONSOLE }} | L1 | AUDIT | Ensure root login is restricted to system console"
  command: cat /etc/securetty
  changed_when: false
  failed_when: false
  check_mode: false
  register: linuxcis_securetty_out

- name: "{{ SEC_ID_ENSURE_ROOT_LOGIN_CONSOLE }} | L1 | AUDIT | Ensure root login is restricted to system console"
  debug:
    msg:
      - "WARNING!!!! Below is the list of consoles with root login access"
      - "Please review for any consoles that are not in a physically secure location"
      - "{{ linuxcis_securetty_out.stdout_lines }}"
