---

# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/considerations_in_adopting_rhel_8/security_considerations-in-adopting-rhel-8
# 8.7.2. securetty is now disabled by default

# this will just display the list of consoles. The site will need to confirm the allowed consoles are correct and change manually if needed.
- name: "{{ SEC_ID_ENSURE_ROOT_LOGIN_CONSOLE }} | L1 | AUDIT | Ensure root login is restricted to system console | Check if securetty file exists"
  stat:
    path: /etc/securetty
  register: linuxcis_securetty_check

- name: "{{ SEC_ID_ENSURE_ROOT_LOGIN_CONSOLE }} | L1 | AUDIT | Ensure root login is restricted to system console | Capture consoles"
  shell: cat /etc/securetty
  changed_when: false
  register: linuxcis_securetty_audit
  when: linuxcis_securetty_check.stat.exists

- name: "{{ SEC_ID_ENSURE_ROOT_LOGIN_CONSOLE }} | L1 | AUDIT |Ensure root login is restricted to system console | Display Console"
  debug:
    msg:
      - "WARNING!!!! Below is the list of consoles with root login access"
      - "Please review for any consoles that are not in a physically secure location"
      - "{{ linuxcis_securetty_audit.stdout_lines }}"
  when: linuxcis_securetty_check.stat.exists

- name: "{{ SEC_ID_ENSURE_ROOT_LOGIN_CONSOLE }} | L1 | AUDIT | Ensure root login is restricted to system console | Display that no securetty file exists"
  debug:
    msg:
      - "There is no /etc/securetty file, this has been removed by default in RHEL8+"
  when: not linuxcis_securetty_check.stat.exists
