---

# TODO: Actually check that /etc/consoletty has not been re-enabled
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/considerations_in_adopting_rhel_8/security_considerations-in-adopting-rhel-8
# 8.7.2. securetty is now disabled by default
- name: "{{ SEC_ID_ENSURE_ROOT_LOGIN_CONSOLE }} | L1 | AUDIT | Ensure root login is restricted to system console "
  debug:
    msg: "INFO: /etc/consoletty disabled by default in RedHat/CentOS 8"
  when:
      - SEC_ID_ENSURE_ROOT_LOGIN_CONSOLE not in disabled_cis_rules
  tags:
      - level1
      - audit
      - rule_5.6
