---

- name: "{{ SEC_ID_ENSURE_SU_COMMAND_RESTRICTED }} | L1 | PATCH | Ensure access to the su command is restricted"
  block:
      - name: "{{ SEC_ID_ENSURE_SU_COMMAND_RESTRICTED }} | L1 | PATCH | Ensure access to the su command is restricted | Setting pam_wheel to use_uid"
        lineinfile:
            state: present
            dest: /etc/pam.d/su
            regexp: '^(#)?auth\s+required\s+pam_wheel\.so'
            line: 'auth            required        pam_wheel.so use_uid {% if linuxcis_sugroup is defined %}group={{ linuxcis_sugroup }}{% endif %}'
        when:
            - SEC_ID_ENSURE_SU_COMMAND_RESTRICTED not in disabled_cis_rules
        tags:
            - level1
            - patch
            - rule_5.7

      - name: "{{ SEC_ID_ENSURE_SU_COMMAND_RESTRICTED }} | L1 | PATCH | Ensure access to the su command is restricted | wheel group contains root"
        group:
            name: root
            groups: "{{ linuxcis_sugroup }}"
  when:
      - SEC_ID_ENSURE_SU_COMMAND_RESTRICTED not in disabled_cis_rules
      - linuxcis_sugroup is defined
  tags:
      - level1
      - patch
      - rule_5.7
