---

- name: "{{ SEC_ID_ENSURE_SU_COMMAND_RESTRICTED }} | L1 | PATCH | Ensure access to the su command is restricted"
  block:
      - name: "{{ SEC_ID_ENSURE_SU_COMMAND_RESTRICTED }} | L1 | PATCH | Ensure access to the su command is restricted | Setting pam_wheel to use_uid"
        lineinfile:
            state: present
            dest: /etc/pam.d/su
            regexp: '^(#)?auth\s+required\s+pam_wheel\.so'
            line: 'auth            required        pam_wheel.so use_uid {% if linuxcis_sugroup is defined %}group={{ linuxcis_sugroup }}{% endif %}'
        when:
            - SEC_ID_ENSURE_SU_COMMAND_RESTRICTED not in disabled_cis_rules
        tags:
            - level1-server
            - level1-workstation
            - patch
            - rule_5.7

      - name: "{{ SEC_ID_ENSURE_SU_COMMAND_RESTRICTED }} | L1 | PATCH | Ensure access to the su command is restricted | wheel group contains root"
        user:
            name: "{{ linuxcis_sugroup_users }}"
            groups: "{{ linuxcis_sugroup | default('wheel') }}"
  when:
      - SEC_ID_ENSURE_SU_COMMAND_RESTRICTED not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_5.7
