---
# Handlers for Linux CIS

- name: sysctl flush ipv4 route table
  become: true
  sysctl:
      name: net.ipv4.route.flush
      value: '1'
      sysctl_set: true
  ignore_errors: true
  when: ansible_virtualization_type != "docker"
  tags:
      - skip_ansible_lint

- name: sysctl flush ipv6 route table
  become: true
  sysctl:
      name: net.ipv6.route.flush
      value: '1'
      sysctl_set: true
  when: ansible_virtualization_type != "docker"

- name: update sysctl
  template:
      src: etc/99-sysctl.conf.j2
      dest: /etc/sysctl.d/99-sysctl.conf
      owner: root
      group: root
      mode: 0600
  notify: reload sysctl
  when:
      - ansible_virtualization_type != "docker"
      - "'procps-ng' in ansible_facts.packages"

- name: reload sysctl
  sysctl:
    name: net.ipv4.route.flush
    value: '1'
    state: present
    reload: true
    ignoreerrors: true
  when:
      - ansible_virtualization_type != "docker"
      - "'systemd' in ansible_facts.packages"

- name: systemd restart tmp.mount
  become: yes
  systemd:
      name: tmp.mount
      daemon_reload: yes
      enabled: yes
      masked: no
      state: reloaded

- name: remount tmp
  command: mount -o remount /tmp
  args:
      warn: false

- name: remount dev_shm
  command: mount -o remount /dev/shm
  args:
      warn: false

- name: remount var_tmp
  command: mount -o remount /var/tmp
  args:
      warn: false

- name: update sysctl
  template:
      src: etc/99-sysctl.conf.j2
      dest: /etc/sysctl.d/99-sysctl.conf
      owner: root
      group: root
      mode: 0600
  notify: reload sysctl
  when:
      - ansible_virtualization_type != "docker"
      - "'procps-ng' in ansible_facts.packages"

- name: reload sysctl
  sysctl:
    name: net.ipv4.route.flush
    value: '1'
    state: present
    reload: true
    ignoreerrors: true
  when:
      - ansible_virtualization_type != "docker"
      - "'systemd' in ansible_facts.packages"

- name: systemd restart var-tmp.mount
  systemd:
      name: var-tmp.mount
      daemon_reload: yes
      enabled: yes
      masked: no
      state: reloaded

- name: remount home
  command: mount -o remount /home
  args:
      warn: false

- name: update dconf
  become: yes
  command: dconf update

- name: restart firewalld
  become: yes
  service:
      name: firewalld
      state: restarted

- name: restart xinetd
  become: yes
  service:
      name: xinetd
      state: restarted

- name: restart sshd
  become: yes
  service:
      name: sshd
      state: restarted

- name: restart postfix
  become: yes
  service:
      name: postfix
      state: restarted

- name: reload dconf
  become: yes
  command: dconf update

- name: update auditd
  template:
      src: audit/99_auditd.rules.j2
      dest: /etc/audit/rules.d/99_auditd.rules
      owner: root
      group: root
      mode: 0600
  notify: restart auditd

- name: restart auditd
  shell: /sbin/service auditd restart
  changed_when: false
  check_mode: false
  failed_when: false
  args:
      warn: false
  when:
      - not linuxcis_skip_for_travis
  tags:
      - skip_ansible_lint

# Used for redhat
- name: grub2cfg
  shell: "grub2-mkconfig -o {{ grub_cfg.stat.lnk_source }}"
  args:
      warn: false
  ignore_errors: True
  tags:
      - skip_ansible_lint

# Used for Ubuntu
- name: update-grub
  command: update-grub

- name: restart rsyslog
  become: yes
  service:
      name: rsyslog
      state: restarted

- name: restart syslog-ng
  become: yes
  service:
      name: syslog-ng
      state: restarted

- name: systemd_daemon_reload
  systemd:
      daemon-reload: true


- name: reload gdm
  command: dpkg-reconfigure gdm3
