---

UEFI_BOOTLOADER_PATH: /boot/efi/EFI/centos/
LEGACY_BOOTLOADER_PATH: /boot/grub2/
GRUB_CFG_PATH: /etc/grub2.cfg
GRUB_RECONFIG_HANDLER: grub2cfg

AIDE_PKG: aide
AUDITD_PKG:
  - audit
  - audit-libs
CRON_PKG: cronie
CRON_SRV: crond
SUDO_PKG: sudo
RPM_GPG_KEY_FILE: /etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial
SELINUX_PKG: libselinux
SETROUBLESHOOT_PKG: setroubleshoot
XORG_PKG: 'xorg-x11-server-*'
XINETD_PKG: xinetd
FIREWALL_PKGS:
  firewalld:
  - firewalld
  nftables:
  - nftables
  iptables:
  - iptables
  - iptables-services
