---
UEFI_BOOTLOADER_PATH: /boot/efi/EFI/ubuntu/
LEGACY_BOOTLOADER_PATH: /boot/grub/
GRUB_CFG_PATH: /boot/grub/grub.cfg
GRUB_RECONFIG_HANDLER: update-grub

AIDE_PKG:
  - aide
  - aide-common
AUDITD_PKG:
  - auditd
  - audispd-plugins
CRON_PKG: cron
GDM_PKG: gdm3
XORG_PKG: 'xserver-xorg*'
FIREWALL_PKGS:
  ufw:
  - ufw
  nftables:
  - nftables
  iptables:
  - iptables
  - iptables-persistent
