---

- name: "PRELIM | Gather system-wide crypto-policy"
  shell: update-crypto-policies --show
  args:
      warn: no
  changed_when: no
  check_mode: no
  register: system_wide_crypto_policy

- name: "PRELIM | Install authconfig"
  package:
      name: authconfig
      state: present
  when:
      - rhel8cis_use_authconfig
      # - rhel8cis_rule_5_3_1 or
      #   rhel8cis_rule_5_3_2 or
      #   rhel8cis_rule_5_3_3
