---

- name: "PRELIM | Run apt update"
  apt:
      update_cache: yes

- name: "PRELIM | Install Network-Manager"
  apt:
      name: network-manager
      state: present
  when:
      - SEC_ID_ENSURE_WIRELESS_INTERFACE_DISABLED not in disabled_cis_rules
      - not linuxcis_system_is_container

- name: "PRELIM | Install ACL"
  apt:
      name: acl
      state: present
  when:
      - SEC_ID_ENSURE_USERS_HOMEDIRS_PERMS not in disabled_cis_rules
      - ubuntucis_install_network_manager
