---

- name: "{{ SEC_ID_ENSURE_DCCP_DISABLED }} | L2 | PATCH | Ensure DCCP is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install dccp(\\s|$)"
      line: "install dccp /bin/true"
      create: yes
      owner: root
      group: root
      mode: 0600
  when:
      - SEC_ID_ENSURE_DCCP_DISABLED not in disabled_cis_rules
      - linuxcis_level2
  tags:
      - level2
      - patch
      - rule_3.4.1

- name: "{{ SEC_ID_ENSURE_SCTP_DISABLED }} | L2 | PATCH | Ensure SCTP is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install sctp(\\s|$)"
      line: "install sctp /bin/true"
      create: yes
      owner: root
      group: root
      mode: 0600
  when:
      - SEC_ID_ENSURE_SCTP_DISABLED not in disabled_cis_rules
      - linuxcis_level2
  tags:
      - level2
      - patch
      - rule_3.4.2
