---

- name: "{{ SEC_ID_ENSURE_RSYSLOG_INSTALLED }} | L1 | PATCH | Ensure rsyslog is installed"
  package:
      name: "{{ linuxcis_syslog }}"
      state: present
  when:
      - SEC_ID_ENSURE_RSYSLOG_INSTALLED not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_4.2.1.1

- name: "{{ SEC_ID_ENSURE_RSYSLOG_ENABLED }} | L1 | PATCH | Ensure rsyslog Service is enabled and running"
  service:
      name: rsyslog
      enabled: yes
      state: started
  when:
      - SEC_ID_ENSURE_RSYSLOG_ENABLED not in disabled_cis_rules
      - linuxcis_syslog == 'rsyslog'
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rsyslog
      - rule_4.2.1.2

- name: "{{ SEC_ID_ENSURE_DEFAULT_FILE_PERMS }} | L1 | PATCH | Ensure rsyslog default file permissions configured"
  lineinfile:
      dest: /etc/rsyslog.conf
      regexp: '^\$FileCreateMode'
      line: '$FileCreateMode 0640'
  notify: restart rsyslog
  when:
      - SEC_ID_ENSURE_DEFAULT_FILE_PERMS not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_4.2.1.3

- name: "{{ SEC_ID_ENSURE_LOGGING_CONFIGURED }} | L1 | PATCH | Ensure logging is configured"
  include_tasks: ensure_logging_configured.yml
  when:
      - SEC_ID_ENSURE_LOGGING_CONFIGURED not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rsyslog
      - rule_4.2.1.4

- name: "{{ SEC_ID_ENSURE_RSYSLOG_REMOTE_LOGGING }} | L1 | PATCH | Ensure rsyslog is configured to send logs to a remote log host"
  blockinfile:
      path: /etc/rsyslog.conf
      state: present
      block: |
        # remote host is: name/ip:port, e.g. 192.168.0.1:514, port optional
        *.* @@{{ linuxcis_remote_log_server }}
      insertafter: EOF
  notify: restart rsyslog
  register: result
  failed_when:
      - result is failed
      - result.rc != 257
  when:
      - SEC_ID_ENSURE_RSYSLOG_REMOTE_LOGGING not in disabled_cis_rules
      - linuxcis_remote_log_server is defined
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_4.2.1.5
      - rsyslog

- name: "{{ SEC_ID_ENSURE_RSYSLOG_ONLY_REMOTE_ACCEPTED }} | L1 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts."
  block:
      - name: "{{ SEC_ID_ENSURE_RSYSLOG_ONLY_REMOTE_ACCEPTED }} | L1 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts. | When not log host"
        replace:
            path: /etc/rsyslog.conf
            regexp: '({{ item }})'
            replace: '#\1'
        with_items:
            - '^(\$ModLoad imtcp)'
            - '^(\$InputTCPServerRun)'
        notify: restart rsyslog
        when:
            - not linuxcis_system_is_log_server

      - name: "{{ SEC_ID_ENSURE_RSYSLOG_ONLY_REMOTE_ACCEPTED }} | L1 | PATCH | Ensure remote rsyslog messages are only accepted on designated log hosts. | When log host"
        replace:
            path: /etc/rsyslog.conf
            regexp: '^#(.*{{ item }}.*)'
            replace: '\1'
        with_items:
            - 'ModLoad imtcp'
            - 'InputTCPServerRun'
        notify: restart rsyslog
        when:
            - linuxcis_system_is_log_server
  when:
      - SEC_ID_ENSURE_RSYSLOG_ONLY_REMOTE_ACCEPTED not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_4.2.1.6
      - rsyslog
