---

- include_tasks: "{{ lookup('first_found', dist_tasks) }}"
  vars:
    dist_tasks:
      - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}.yml"
      - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
      - "{{ ansible_facts.distribution }}.yml"
      - "{{ ansible_facts.os_family }}.yml"
