---

- name: "{{ SEC_ID_ENSURE_NFTABLES_NOT_ENABLED_WITH_FIREWALLD }} | L1 | PATCH | Ensure nftables-services is absent with firewalld"
  systemd:
      name: iptables
      state: stopped
      masked: yes
  when:
      - "'iptables' in ansible_facts.packages"
