---

- name: "{{ SEC_ID_ENSURE_NETWORK_INTERFACES_ASSIGNED_TO_APPROPRIATE_USE }} | L1 | AUDIT | Ensure network interfaces are assigned to appropriate zone | Get list of interfaces and policies"
  shell: "nmcli -t connection show | awk -F: '{ if($4){print $4} }' | while read INT; do firewall-cmd --get-active-zones | grep -B1 $INT; done"
  changed_when: false
  failed_when: false
  check_mode: false
  register: linuxcis_firewalld_interfacepolicy_out
  tags: always

- name: "{{ SEC_ID_ENSURE_NETWORK_INTERFACES_ASSIGNED_TO_APPROPRIATE_USE }} | L1 | AUDIT | Ensure network interfaces are assigned to appropriate zone | Get list of interfaces and policies | Show the interface to policy"
  debug:
      msg:
          - "The items below are the policies tied to the interfaces, please correct as needed"
          - "{{ linuxcis_firewalld_interfacepolicy_out.stdout_lines }}"
  tags: always
