---

galaxy_info:
  author: "Sam Doran, Josh Springer, Daniel Shepherd, Bas Meijeri, James Cassell, Mike Renfro, DFed, Mark Bolwell, George Nalen, Konstantinos Thoukydidis"
  description: "This role applies the CIS Linux Hardening role"
  company: "MindPoint Group, Others"
  license: MIT
  min_ansible_version: 2.10.0
  role_name: linux_cis
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
    - name: Ubuntu
      versions:
        - focal
        - bionic
    - name: Debian
      versions:
        - stretch
        - buster
  galaxy_tags:
    - system
    - security
    - cis
    - hardening
    - el
    - redhat
    - centos
    - debian
    - ubuntu
dependencies: []
