---

- name: "{{ SEC_ID_ENSURE_FIREWALLD_INSTALLED }} | L1 | PATCH | Ensure FirewallD is installed"
  package:
      name: firewalld
      state: present
#   vars:
#       ansible_python_interpreter: /bin/python
  when:
      - SEC_ID_ENSURE_FIREWALLD_INSTALLED not in disabled_cis_rules
  tags:
      - level1
      - patch
      - rule_3.5.1.1

- name: "{{ SEC_ID_ENSURE_IPTABLES_NOT_INSTALLED_WITH_FIREWALLD }} | L1 | PATCH | Ensure iptables-services not installed with firewalld"
  package:
      name: iptables-services
      state: absent
  when:
      - SEC_ID_ENSURE_IPTABLES_NOT_INSTALLED_WITH_FIREWALLD not in disabled_cis_rules
  tags:
      - level1
      - patch
      - rule_3.5.1.2

- name: "{{ SEC_ID_ENSURE_NFTABLES_DISABLED_WITH_FIREWALLD }} | L1 | PATCH | Ensure nftables-services not installed along with firewalld | Import Distriution-dependent-tasks"
  include_tasks: "{{ lookup('first_found', dist_tasks) }}"
  vars:
    dist_tasks:
      - "disable_nftables_with_firewalld_{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}.yml"
      - "disable_nftables_with_firewalld_{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
      - "disable_nftables_with_firewalld_{{ ansible_facts.distribution }}.yml"
      - "disable_nftables_with_firewalld_{{ ansible_facts.os_family }}.yml"
  when:
      - SEC_ID_ENSURE_NFTABLES_DISABLED_WITH_FIREWALLD not in disabled_cis_rules
  tags:
      - level1
      - patch
      - rule_3.5.1.3

- name: "{{ SEC_ID_ENSURE_FIREWALLD_SERVICE_ENABLED }} | L1 | PATCH | Ensure firewalld service is enabled and running"
  systemd:
      name: firewalld
      state: started
      enabled: true
      masked: false
  when:
      - SEC_ID_ENSURE_FIREWALLD_SERVICE_ENABLED not in disabled_cis_rules
  tags:
      - level1
      - patch
      - rule_3.5.1.4

- name: "{{ SEC_ID_ENSURE_FIREWALLD_DEFAULT_ZONE_NOT_SET }} | L1 | PATCH | Ensure firewalld default zone is set"
  block:
      - name: "3.5.1.5 | L1 | AUDIT | Ensure default zone is set"
        command: firewall-cmd --get-default-zone
        changed_when: false
        register: current_default_zone

      - name: "3.5.1.5 | L1 | PATCH | Ensure default zone is set"
        command: firewall-cmd --set-default-zone="{{ linuxcis_default_zone }}"
        when:
            - current_default_zone.stdout != linuxcis_default_zone
  when:
      - SEC_ID_ENSURE_FIREWALLD_DEFAULT_ZONE_NOT_SET not in disabled_cis_rules
  tags:
      - level1
      - patch
      - rule_3.5.1.5

- name: "{{ SEC_ID_ENSURE_NETWORK_INTERFACES_ASSIGNED_TO_APPROPRIATE_USE }} | L1 | AUDIT | Ensure network interfaces are assigned to appropriate zone"
  block:
      - name: "{{ SEC_ID_ENSURE_NETWORK_INTERFACES_ASSIGNED_TO_APPROPRIATE_USE }} | L1 | AUDIT | Ensure network interfaces are assigned to appropriate zone | Get list of interfaces and policies"
        shell: "nmcli -t connection show | awk -F: '{ if($4){print $4} }' | while read INT; do firewall-cmd --get-active-zones | grep -B1 $INT; done"
        register: linuxcis_3_5_1_6_interfacepolicy
        changed_when: false
        become: yes

      - name: "{{ SEC_ID_ENSURE_NETWORK_INTERFACES_ASSIGNED_TO_APPROPRIATE_USE }} | L1 | AUDIT | Ensure network interfaces are assigned to appropriate zone | Get list of interfaces and policies | Show the interface to policy"
        debug:
            msg:
                - "The items below are the policies tied to the interfaces, please correct as needed"
                - "{{ linuxcis_3_5_1_6_interfacepolicy.stdout_lines }}"
  when:
      - SEC_ID_ENSURE_NETWORK_INTERFACES_ASSIGNED_TO_APPROPRIATE_USE not in disabled_cis_rules
  tags:
      - level1
      - audit
      - rule_3.5.1.6

- name: "{{ SEC_ID_ENSURE_FIREWALLD_DROPS_UNNECESSARY_SERVICES_PORTS }} | L1 | AUDIT | Ensure firewalld drops unnecessary services and ports"
  block:
      - name: "{{ SEC_ID_ENSURE_FIREWALLD_DROPS_UNNECESSARY_SERVICES_PORTS }} | L1 | AUDIT | Ensure firewalld drops unnecessary services and ports | Get list of services and ports"
        shell: "firewall-cmd --get-active-zones | awk '!/:/ {print $1}' | while read ZN; do firewall-cmd --list-all --zone=$ZN; done"
        register: linuxcis_3_5_1_7_servicesport
        become: true
        changed_when: no

      - name: "{{ SEC_ID_ENSURE_FIREWALLD_DROPS_UNNECESSARY_SERVICES_PORTS }} | L1 | AUDIT | Ensure firewalld drops unnecessary services and ports | Show services and ports"
        debug:
            msg:
                - "The items below are the services and ports that are accepted, please correct as needed"
                - "{{ linuxcis_3_5_1_7_servicesport.stdout_lines }}"
  when:
      - SEC_ID_ENSURE_FIREWALLD_DROPS_UNNECESSARY_SERVICES_PORTS not in disabled_cis_rules
  tags:
      - level1
      - audit
      - rule_3.5.1.7
