---

- name: "{{ SEC_ID_ENSURE_IPTABLES_INSTALLED }} | L1 | PATCH | Ensure iptables packages are installed"
  package:
      name: "{{ item }}"
      state: present
  loop:
      - iptables
      - iptables-services
#   vars:
#       ansible_python_interpreter: /bin/python
  when:
      - SEC_ID_ENSURE_IPTABLES_INSTALLED not in disabled_cis_rules
  tags:
      - level1
      - patch
      - rule_3.5.3.1

- name: "{{ SEC_ID_ENSURE_NFTABLES_NOT_INSTALLED_WITH_IPTABLES }} | L1 | PATCH | Ensure nftables is not installed with iptables"
  package:
      name: nftables
      state: absent
#   vars:
#       ansible_python_interpreter: /bin/python
  when:
      - SEC_ID_ENSURE_NFTABLES_NOT_INSTALLED_WITH_IPTABLES not in disabled_cis_rules
  tags:
      - level1
      - patch
      - rule_3.5.3.2

- name: "{{ SEC_ID_ENSURE_FIREWALLD_NOT_INSTALLED_WITH_IPTABLES }} | L1 | PATCH | Ensure firewalld is either not installed or masked with iptables"
  package:
      name: firewalld
      state: absent
#   vars:
#       ansible_python_interpreter: /bin/python
  when:
      - SEC_ID_ENSURE_FIREWALLD_NOT_INSTALLED_WITH_IPTABLES not in disabled_cis_rules
  tags:
      - level1
      - patch
      - rule_3.5.3.3

# Rest of the rules are TODO
