---

- name: "SECTION | {{ SEC_ID_ENSURE_IPTABLES_INSTALLED }} | Ensure iptables packages are installed"
  include_tasks: ensure_firewall_package_installed_Ubuntu.yml
  vars:
    cis_section: "{{ SEC_ID_ENSURE_IPTABLES_INSTALLED }}"
    cis_section_description: "Ensure iptables is installed"
  when:
  - SEC_ID_ENSURE_IPTABLES_INSTALLED not in disabled_cis_rules
  tags:
  - level1-server
  - level1-workstation
  - patch
  - rule_3.5.1.1

- name: "{{ SEC_ID_ENSURE_NFTABLES_NOT_INSTALLED_WITH_IPTABLES }} | L1 | PATCH | Ensure nftables is not installed with iptables"
  apt:
      name: nftables
      state: absent
  when:
      - SEC_ID_ENSURE_NFTABLES_NOT_INSTALLED_WITH_IPTABLES not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_3.5.3.1.2
      - iptables

- name: "{{ SEC_ID_ENSURE_UFW_NOT_INSTALLED_WITH_IPTABLES }} | L1 | PATCH | Ensure ufw is uninstalled or disabled with iptables"
  apt:
      name: ufw
      state: absent
  when:
      - SEC_ID_ENSURE_UFW_NOT_INSTALLED_WITH_IPTABLES not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_3.5.3.1.3
      - iptables

- name: "SECTION | {{ SEC_ID_CONFIGURE_IPTABLES }} | Configure iptables | IPv4"
  include_tasks: iptables/configure_iptables_ipv4.yml

- name: "SECTION | {{ SEC_ID_CONFIGURE_IPTABLES }} | Configure iptables | IPv6"
  include_tasks: iptables/configure_iptables_ipv6.yml
  when:
  - linuxcis_ipv6_required

# # ---------------
# # ---------------
# # This is not a control however using the iptables and ip6tables module only writes to memery
# # if a reboot occurs that means changes can revert. This task will make the
# # above iptables settings permanent
# # ---------------
# # ---------------
# - name: "Make IPTables persistent | Not a control"
#   shell: bash -c "iptables-save > /etc/iptables/rules.v4"
#   changed_when: ubuntu20cis_iptables_save.rc == 0
#   failed_when: ubuntu20cis_iptables_save.rc > 0
#   register: ubuntu20cis_iptables_save
#   when:
#       - SEC_ID_ENSURE_IPTABLES_LOOPBACK_TRAFFIC_CONFIGURED not in disabled_cis_rules or
#         SEC_ID_ENSURE_IPTABLES_OUTBOUND_AND_ESTABLISHED_CONNECTION_CONFIGURED not in disabled_cis_rules or
#         SEC_ID_ENSURE_IPTABLES_DEFAULT_DENY_FIREWALL_POLICY not in disabled_cis_rules or
#         SEC_ID_ENSURE_IPTABLES_FIREWALL_RULES_EXIST_FOR_OPEN_PORTS not in disabled_cis_rules

# - name: "Make IP6Tables persistent | Not a CIS control"
#   shell: bash -c "ip6tables-save > /etc/iptables/rules.v6"
#   changed_when: debiancis_ip6tables_save.rc == 0
#   failed_when: debiancis_ip6tables_save.rc > 0
#   register: debiancis_ip6tables_save
#   when:
#       - linuxcis_ipv6_required
#       - SEC_ID_ENSURE_IP6TABLES_LOOPBACK_TRAFFIC_CONFIGURED not in disabled_cis_rules or
#         SEC_ID_ENSURE_IP6TABLES_OUTBOUND_AND_ESTABLISHED_CONNECTION_CONFIGURED not in disabled_cis_rules or
#         SEC_ID_ENSURE_IP6TABLES_DEFAULT_DENY_FIREWALL_POLICY not in disabled_cis_rules or
#         SEC_ID_ENSURE_IP6TABLES_FIREWALL_RULES_EXIST_FOR_OPEN_PORTS not in disabled_cis_rules
