---

- name: "{{ SEC_ID_ENSURE_CORE_DUMPS_ARE_RESTRICED }} | L1 | AUDIT | Ensure XD/NX support is enabled | Find status of XD/NX"
  shell: "journalctl | grep 'protection: active'"
  changed_when: false
  failed_when: false
  check_mode: false
  register: linuxcis_xdnx_status

- name: "{{ SEC_ID_ENSURE_CORE_DUMPS_ARE_RESTRICED }} | L1 | AUDIT | Ensure XD/NX support is enabled | Alert if XD/NX is not enabled"
  debug:
      msg:
          - "ALERT!!!!You do not have XD/NX (Execute Disable/No Execute) enabled"
          - "To conform to CIS standards this needs to be enabled"
  when: "'active'not in linuxcis_xdnx_status.stdout"
