---

- name: "{{ SEC_ID_ENSURE_CORE_DUMPS_ARE_RESTRICED }} | L1 | Ensure core dumps are restricted | Update limits.conf file"
  lineinfile:
      path: /etc/security/limits.d/99_zero_core.conf
      regexp: '^\* hard core'
      line: '* hard core 0'
      create: true
      owner: root
      group: root
      mode: '0644'
  tags: always

- name: "{{ SEC_ID_ENSURE_CORE_DUMPS_ARE_RESTRICED }} | L1 | PATCH | Ensure core dumps are restricted | Set active kernel parameter"
  debug:
      msg: "Control being set via Handler 'update sysctl' which writes to /etc/sysctl.d/99-sysctl.conf"
  notify:
      - update sysctl
  tags: always

- name: "{{ SEC_ID_ENSURE_CORE_DUMPS_ARE_RESTRICED }} | L1 | PATCH | Ensure core dumps are restricted | if systemd coredump"
  lineinfile:
      path: /etc/systemd/coredump.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.regexp }}{{ item.line }}"
      state: present
      mode: 0644
  loop:
      - {'regexp': 'Storage=', 'line': 'none'}
      - {'regexp': 'ProcessSizeMax=', 'line': '0'}
  notify:
      - systemd_daemon_reload
  when:
      - systemd_coredump.stat.exists
  tags: always
