---

- name: "{{ SEC_ID_ENSURE_CORE_DUMPS_ARE_RESTRICED }} | L1 | PATCH | Ensure core dumps are restricted"
  block:
      - name: "{{ SEC_ID_ENSURE_CORE_DUMPS_ARE_RESTRICED }} | L1 | PATCH | Ensure core dumps are restricted | Update limits.conf file"
        lineinfile:
            state: present
            dest: /etc/security/limits.conf
            regexp: '^#?\\*.*core'
            line: '*                hard    core            0'
            insertbefore: '^# End of file'

      - name: "{{ SEC_ID_ENSURE_CORE_DUMPS_ARE_RESTRICED }} | L1 | PATCH | Ensure core dumps are restricted | Set active kernel parameter"
        sysctl:
            name: fs.suid_dumpable
            value: '0'
            state: present
            reload: yes
            sysctl_set: yes
            ignoreerrors: yes

      - name: "{{ SEC_ID_ENSURE_CORE_DUMPS_ARE_RESTRICED }} | L1 | PATCH | Ensure core dumps are restricted | coredump.conf"
        lineinfile:
            dest: /etc/systemd/coredump.conf
            regexp: "{{ item.regex }}"
            line: "{{ item.line }}"
            create: yes
            mode: 0644
        loop:
            - { regex: '^Storage', line: 'Storage=none' }
            - { regex: '^ProcessSizeMax', line: 'ProcessSizeMax=0' }
  when:
      - SEC_ID_ENSURE_CORE_DUMPS_ARE_RESTRICED not in disabled_cis_rules
  tags:
      - level1
      - sysctl
      - patch
      - rule_1.5.1

- name: "{{ SEC_ID_ENSURE_NX_ND_SUPPORT_ENABLED }} | L1 | PATCH | Ensure XD/NX support is enabled"
  shell: dmesg|grep -E "NX|XD" | grep " active"
  changed_when: false
  when:
      - SEC_ID_ENSURE_NX_ND_SUPPORT_ENABLED not in disabled_cis_rules
  tags:
      - skip_ansible_lint
      - level1
      - patch
      - rule_1.5.2

- name: "{{ SEC_ID_ENSURE_ADDRESS_SPACE_RANDOMIZATION_ENABLED }} | L1 | PATCH | Ensure address space layout randomization (ASLR) is enabled"
  sysctl:
      name: kernel.randomize_va_space
      value: '2'
      state: present
      reload: yes
      sysctl_set: yes
      ignoreerrors: yes
  when:
      - SEC_ID_ENSURE_ADDRESS_SPACE_RANDOMIZATION_ENABLED not in disabled_cis_rules
  tags:
      - level1
      - patch
      - rule_1.5.3

- name: "{{ SEC_ID_ENSURE_PRELINK_NOT_INSTALLED }} | L1 | PATCH | Ensure prelink is disabled"
  package:
      name: prelink
      state: absent
  when:
      - SEC_ID_ENSURE_PRELINK_NOT_INSTALLED not in disabled_cis_rules
  tags:
      - level1
      - patch
      - rule_1.5.4
#   vars:
#       ansible_python_interpreter: /bin/python
