---

- name: "{{ SEC_ID_ENSURE_CORE_DUMPS_ARE_RESTRICED }} | L1 | PATCH | Ensure core dumps are restricted"
  include_tasks: "ensure_core_dumps_restricted.yml"
  when:
      - SEC_ID_ENSURE_CORE_DUMPS_ARE_RESTRICED not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - scored
      - sysctl
      - patch
      - rule_1.6.1

- name: "{{ SEC_ID_ENSURE_ADDRESS_SPACE_RANDOMIZATION_ENABLED }} | L1 | PATCH | Ensure address space layout randomization (ASLR) is enabled"
  debug:
      msg: "Control being set via Handler 'update sysctl' which writes to /etc/sysctl.d/99-sysctl.conf"
  notify:
      - update sysctl
  when:
      - SEC_ID_ENSURE_ADDRESS_SPACE_RANDOMIZATION_ENABLED not in disabled_cis_rules
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.6.2
