---

- name: "{{ SEC_ID_AIDE_SETUP }} |L1 | PATCH | Ensure AIDE is setup | initialize"
  command: aideinit -d /var/lib/aide/aide.db
  args:
    creates: /var/lib/aide/aide.db
  changed_when: false
  failed_when: false
  async: 45
  poll: 0
