---

- name: "{{ SEC_ID_AIDE_SETUP }} | L1 | PATCH | Ensure AIDE is setup"
  block:
  - name: "{{ SEC_ID_AIDE_SETUP }} | L1 | PATCH | Ensure AIDE is setup | Install AIDE"
    apt:
      name:
      - aide
      - aide-common
      state: present

  - name: "{{ SEC_ID_AIDE_SETUP }} |L1 | PATCH | Ensure AIDE is setup | initialize"
    shell: /usr/sbin/aide --init -B 'database_out=file:/var/lib/aide/aide.db.gz'
    args:
      creates: /var/lib/aide/aide.db.gz
    changed_when: false
    failed_when: false
    async: 45
    poll: 0
  when:
    - linuxcis_config_aide
    - SEC_ID_AIDE_SETUP not in disabled_cis_rules
  tags:
    - level1-server
    - level1-workstation
    - scored
    - aide
    - patch
    - rule_1.4.1


- name: "{{ SEC_ID_AIDE_SCHEDULE }} | L1 | PATCH | Ensure filesystem integrity is regularly checked | cron"
  template:
    src: aide.cron.j2
    dest: /etc/cron.d/aide.cron
    owner: root
    group: root
    mode: 0644
  when:
    - SEC_ID_AIDE_SCHEDULE not in disabled_cis_rules
  tags:
    - level1-server
    - level1-workstation
    - scored
    - aide
    - file_integrity
    - patch
    - rule_1.4.2
