---

- name: "{{ SEC_ID_AIDE_SETUP }} | L1 | PATCH | Ensure AIDE is setup"
  block:
  - name: "{{ SEC_ID_AIDE_SETUP }} | L1 | PATCH | Ensure AIDE is setup | Install AIDE"
    package:
      name: "{{ AIDE_PKG }}"
      state: present

  - name: "{{ SEC_ID_AIDE_SETUP }} |L1 | PATCH | Ensure AIDE is setup | Initialize | Distribution-dependent tasks"
    include_tasks: "{{ lookup('first_found', dist_tasks) }}"
    vars:
      dist_tasks:
        - "initialize_aide_{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "initialize_aide_{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "initialize_aide_{{ ansible_facts.distribution }}.yml"
        - "initialize_aide_{{ ansible_facts.os_family }}.yml"
  when:
    - linuxcis_config_aide
    - SEC_ID_AIDE_SETUP not in disabled_cis_rules
  tags:
    - level1-server
    - level1-workstation
    - scored
    - aide
    - patch
    - rule_1.4.1


- name: "{{ SEC_ID_AIDE_SCHEDULE }} | L1 | PATCH | Ensure filesystem integrity is regularly checked | cron"
  template:
    src: aide.cron.j2
    dest: /etc/cron.d/aide.cron
    owner: root
    group: root
    mode: 0644
  when:
    - SEC_ID_AIDE_SCHEDULE not in disabled_cis_rules
  tags:
    - level1-server
    - level1-workstation
    - scored
    - aide
    - file_integrity
    - patch
    - rule_1.4.2
