---

- name: "{{ SEC_ID_NON_ESSENTIAL_SERVICES }} | L1 | Ensure nonessential services are removed or masked (Manual)"
  block:
      - name: "{{ SEC_ID_NON_ESSENTIAL_SERVICES }} | L1 | AUDIT | Ensure nonessential services are removed or masked | Check for services"
        shell: lsof -i -P -n | grep -v "(ESTABLISHED)"
        changed_when: false
        failed_when: false
        check_mode: false
        register: linuxcis_non_essential_services_out

      - name: "{{ SEC_ID_NON_ESSENTIAL_SERVICES }} | L1 | AUDIT | Ensure nonessential services are removed or masked | Message out running services"
        debug:
            msg:
                - "Warning!! Below are the running services. Please review and remove as well as mask un-needed services"
                - "{{ linuxcis_non_essential_services_out.stdout_lines }}"
  when:
      - SEC_ID_NON_ESSENTIAL_SERVICES not in disabled_cis_rules
  tags:
      - level1
      - notscored
      - rule_2.4
